// src/lib/translate.js
// Translation system with support for multiple languages

import { languages } from '../data/languages';

// Translation data
const translations = {
  en: {
    // Common
    welcome: 'Welcome',
    shop_now: 'Shop Now',
    view_collections: 'View Collections',
    featured_products: 'Featured Products',
    categories: 'Categories',
    search: 'Search',
    cart: 'Cart',
    wishlist: 'Wishlist',
    account: 'Account',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    profile: 'Profile',
    orders: 'Orders',
    settings: 'Settings',
    help: 'Help',
    contact: 'Contact',
    about: 'About',
    privacy: 'Privacy Policy',
    terms: 'Terms & Conditions',
    returns: 'Returns Policy',
    shipping: 'Shipping Info',
    faq: 'FAQ',
    blog: 'Blog',
    // Products
    add_to_cart: 'Add to Cart',
    buy_now: 'Buy Now',
    out_of_stock: 'Out of Stock',
    in_stock: 'In Stock',
    low_stock: 'Low Stock',
    price: 'Price',
    quantity: 'Quantity',
    total: 'Total',
    subtotal: 'Subtotal',
    tax: 'Tax',
    shipping_charge: 'Shipping Charge',
    discount: 'Discount',
    coupon: 'Coupon',
    apply_coupon: 'Apply Coupon',
    // Cart
    cart_empty: 'Your cart is empty',
    cart_total: 'Cart Total',
    checkout: 'Checkout',
    proceed_to_checkout: 'Proceed to Checkout',
    continue_shopping: 'Continue Shopping',
    // Footer
    copyright: 'All rights reserved',
    follow_us: 'Follow Us',
    newsletter: 'Newsletter',
    subscribe: 'Subscribe',
    // Admin
    dashboard: 'Dashboard',
    products: 'Products',
    add_product: 'Add Product',
    edit_product: 'Edit Product',
    delete_product: 'Delete Product',
    orders_management: 'Orders Management',
    customers: 'Customers',
    drivers: 'Drivers',
    analytics: 'Analytics',
    reports: 'Reports',
    // Common actions
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    update: 'Update',
    create: 'Create',
    remove: 'Remove',
    confirm: 'Confirm',
    close: 'Close',
  },
  ta: {
    welcome: 'வரவேற்கிறோம்',
    shop_now: 'இப்போது ஷாப்பிங் செய்யுங்கள்',
    view_collections: 'தொகுப்புகளை காண்க',
    featured_products: 'சிறப்பு பொருட்கள்',
    categories: 'வகைகள்',
    search: 'தேடு',
    cart: 'கார்ட்',
    wishlist: 'விருப்பப் பட்டியல்',
    account: 'கணக்கு',
    login: 'உள்நுழைய',
    register: 'பதிவு செய்ய',
    logout: 'வெளியேறு',
    profile: 'சுயவிவரம்',
    orders: 'ஆர்டர்கள்',
    settings: 'அமைப்புகள்',
    help: 'உதவி',
    contact: 'தொடர்பு',
    about: 'பற்றி',
    privacy: 'தனியுரிமைக் கொள்கை',
    terms: 'விதிமுறைகள்',
    returns: 'திரும்பப் பெறும் கொள்கை',
    shipping: 'ஷிப்பிங் தகவல்',
    faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    blog: 'வலைப்பதிவு',
    add_to_cart: 'கார்டில் சேர்',
    buy_now: 'இப்போது வாங்க',
    out_of_stock: 'கையிருப்பில் இல்லை',
    in_stock: 'கையிருப்பில் உள்ளது',
    low_stock: 'குறைந்த கையிருப்பு',
    price: 'விலை',
    quantity: 'அளவு',
    total: 'மொத்தம்',
    subtotal: 'கூட்டுத்தொகை',
    tax: 'வரி',
    shipping_charge: 'ஷிப்பிங் கட்டணம்',
    discount: 'தள்ளுபடி',
    coupon: 'கூப்பன்',
    apply_coupon: 'கூப்பனைப் பயன்படுத்து',
    cart_empty: 'உங்கள் கார்ட் காலியாக உள்ளது',
    cart_total: 'கார்ட் மொத்தம்',
    checkout: 'செக்-அவுட்',
    proceed_to_checkout: 'செக்-அவுட்டுக்கு செல்லவும்',
    continue_shopping: 'ஷாப்பிங் தொடரவும்',
    copyright: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை',
    follow_us: 'எங்களைப் பின்தொடரவும்',
    newsletter: 'செய்திமடல்',
    subscribe: 'பதிவு செய்யவும்',
    dashboard: 'டாஷ்போர்ட்',
    products: 'பொருட்கள்',
    add_product: 'பொருளை சேர்',
    edit_product: 'பொருளை திருத்து',
    delete_product: 'பொருளை நீக்கு',
    orders_management: 'ஆர்டர்கள் மேலாண்மை',
    customers: 'வாடிக்கையாளர்கள்',
    drivers: 'ஓட்டுநர்கள்',
    analytics: 'பகுப்பாய்வு',
    reports: 'அறிக்கைகள்',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    update: 'புதுப்பி',
    create: 'உருவாக்கு',
    remove: 'அகற்று',
    confirm: 'உறுதி செய்',
    close: 'மூடு',
  },
  hi: {
    welcome: 'स्वागत है',
    shop_now: 'अभी खरीदें',
    view_collections: 'संग्रह देखें',
    featured_products: 'विशेष उत्पाद',
    categories: 'श्रेणियाँ',
    search: 'खोज',
    cart: 'कार्ट',
    wishlist: 'इच्छा सूची',
    account: 'खाता',
    login: 'लॉगिन',
    register: 'पंजीकरण करें',
    logout: 'लॉगआउट',
    profile: 'प्रोफ़ाइल',
    orders: 'ऑर्डर',
    settings: 'सेटिंग्स',
    help: 'सहायता',
    contact: 'संपर्क करें',
    about: 'हमारे बारे में',
    privacy: 'गोपनीयता नीति',
    terms: 'नियम और शर्तें',
    returns: 'वापसी नीति',
    shipping: 'शिपिंग जानकारी',
    faq: 'अक्सर पूछे जाने वाले प्रश्न',
    blog: 'ब्लॉग',
    add_to_cart: 'कार्ट में डालें',
    buy_now: 'अभी खरीदें',
    out_of_stock: 'स्टॉक से बाहर',
    in_stock: 'स्टॉक में',
    low_stock: 'कम स्टॉक',
    price: 'कीमत',
    quantity: 'मात्रा',
    total: 'कुल',
    subtotal: 'उप-योग',
    tax: 'कर',
    shipping_charge: 'शिपिंग शुल्क',
    discount: 'छूट',
    coupon: 'कूपन',
    apply_coupon: 'कूपन लागू करें',
    cart_empty: 'आपकी कार्ट खाली है',
    cart_total: 'कार्ट कुल',
    checkout: 'चेकआउट',
    proceed_to_checkout: 'चेकआउट के लिए आगे बढ़ें',
    continue_shopping: 'खरीदारी जारी रखें',
    copyright: 'सभी अधिकार सुरक्षित',
    follow_us: 'हमें फॉलो करें',
    newsletter: 'समाचार पत्र',
    subscribe: 'सदस्यता लें',
    dashboard: 'डैशबोर्ड',
    products: 'उत्पाद',
    add_product: 'उत्पाद जोड़ें',
    edit_product: 'उत्पाद संपादित करें',
    delete_product: 'उत्पाद हटाएं',
    orders_management: 'ऑर्डर प्रबंधन',
    customers: 'ग्राहक',
    drivers: 'ड्राइवर',
    analytics: 'विश्लेषण',
    reports: 'रिपोर्ट',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    update: 'अपडेट करें',
    create: 'बनाएं',
    remove: 'हटाएं',
    confirm: 'पुष्टि करें',
    close: 'बंद करें',
  },
  fr: {
    welcome: 'Bienvenue',
    shop_now: 'Acheter maintenant',
    view_collections: 'Voir les collections',
    featured_products: 'Produits vedettes',
    categories: 'Catégories',
    search: 'Rechercher',
    cart: 'Panier',
    wishlist: 'Liste de souhaits',
    account: 'Compte',
    login: 'Se connecter',
    register: 'S\'inscrire',
    logout: 'Se déconnecter',
    profile: 'Profil',
    orders: 'Commandes',
    settings: 'Paramètres',
    help: 'Aide',
    contact: 'Contact',
    about: 'À propos',
    privacy: 'Politique de confidentialité',
    terms: 'Conditions générales',
    returns: 'Politique de retour',
    shipping: 'Informations de livraison',
    faq: 'FAQ',
    blog: 'Blog',
    add_to_cart: 'Ajouter au panier',
    buy_now: 'Acheter maintenant',
    out_of_stock: 'Rupture de stock',
    in_stock: 'En stock',
    low_stock: 'Stock faible',
    price: 'Prix',
    quantity: 'Quantité',
    total: 'Total',
    subtotal: 'Sous-total',
    tax: 'Taxe',
    shipping_charge: 'Frais de livraison',
    discount: 'Remise',
    coupon: 'Code promo',
    apply_coupon: 'Appliquer le code',
    cart_empty: 'Votre panier est vide',
    cart_total: 'Total du panier',
    checkout: 'Passer la commande',
    proceed_to_checkout: 'Procéder au paiement',
    continue_shopping: 'Continuer les achats',
    copyright: 'Tous droits réservés',
    follow_us: 'Suivez-nous',
    newsletter: 'Newsletter',
    subscribe: 'S\'abonner',
    dashboard: 'Tableau de bord',
    products: 'Produits',
    add_product: 'Ajouter un produit',
    edit_product: 'Modifier le produit',
    delete_product: 'Supprimer le produit',
    orders_management: 'Gestion des commandes',
    customers: 'Clients',
    drivers: 'Chauffeurs',
    analytics: 'Analytique',
    reports: 'Rapports',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    update: 'Mettre à jour',
    create: 'Créer',
    remove: 'Retirer',
    confirm: 'Confirmer',
    close: 'Fermer',
  },
  de: {
    welcome: 'Willkommen',
    shop_now: 'Jetzt einkaufen',
    view_collections: 'Kollektionen anzeigen',
    featured_products: 'Ausgewählte Produkte',
    categories: 'Kategorien',
    search: 'Suchen',
    cart: 'Warenkorb',
    wishlist: 'Wunschliste',
    account: 'Konto',
    login: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    profile: 'Profil',
    orders: 'Bestellungen',
    settings: 'Einstellungen',
    help: 'Hilfe',
    contact: 'Kontakt',
    about: 'Über uns',
    privacy: 'Datenschutz',
    terms: 'AGB',
    returns: 'Rückgaberecht',
    shipping: 'Versandinfo',
    faq: 'FAQ',
    blog: 'Blog',
    add_to_cart: 'In den Warenkorb',
    buy_now: 'Jetzt kaufen',
    out_of_stock: 'Nicht vorrätig',
    in_stock: 'Auf Lager',
    low_stock: 'Niedriger Bestand',
    price: 'Preis',
    quantity: 'Menge',
    total: 'Gesamt',
    subtotal: 'Zwischensumme',
    tax: 'Steuer',
    shipping_charge: 'Versandkosten',
    discount: 'Rabatt',
    coupon: 'Gutschein',
    apply_coupon: 'Gutschein anwenden',
    cart_empty: 'Ihr Warenkorb ist leer',
    cart_total: 'Warenkorb gesamt',
    checkout: 'Zur Kasse',
    proceed_to_checkout: 'Zur Kasse gehen',
    continue_shopping: 'Weiter einkaufen',
    copyright: 'Alle Rechte vorbehalten',
    follow_us: 'Folgen Sie uns',
    newsletter: 'Newsletter',
    subscribe: 'Abonnieren',
    dashboard: 'Dashboard',
    products: 'Produkte',
    add_product: 'Produkt hinzufügen',
    edit_product: 'Produkt bearbeiten',
    delete_product: 'Produkt löschen',
    orders_management: 'Bestellverwaltung',
    customers: 'Kunden',
    drivers: 'Fahrer',
    analytics: 'Analytik',
    reports: 'Berichte',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    update: 'Aktualisieren',
    create: 'Erstellen',
    remove: 'Entfernen',
    confirm: 'Bestätigen',
    close: 'Schließen',
  },
  es: {
    welcome: 'Bienvenido',
    shop_now: 'Comprar ahora',
    view_collections: 'Ver colecciones',
    featured_products: 'Productos destacados',
    categories: 'Categorías',
    search: 'Buscar',
    cart: 'Carrito',
    wishlist: 'Lista de deseos',
    account: 'Cuenta',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    logout: 'Cerrar sesión',
    profile: 'Perfil',
    orders: 'Pedidos',
    settings: 'Configuración',
    help: 'Ayuda',
    contact: 'Contacto',
    about: 'Acerca de',
    privacy: 'Política de privacidad',
    terms: 'Términos y condiciones',
    returns: 'Política de devolución',
    shipping: 'Información de envío',
    faq: 'Preguntas frecuentes',
    blog: 'Blog',
    add_to_cart: 'Añadir al carrito',
    buy_now: 'Comprar ahora',
    out_of_stock: 'Agotado',
    in_stock: 'En stock',
    low_stock: 'Stock bajo',
    price: 'Precio',
    quantity: 'Cantidad',
    total: 'Total',
    subtotal: 'Subtotal',
    tax: 'Impuesto',
    shipping_charge: 'Gastos de envío',
    discount: 'Descuento',
    coupon: 'Cupón',
    apply_coupon: 'Aplicar cupón',
    cart_empty: 'Tu carrito está vacío',
    cart_total: 'Total del carrito',
    checkout: 'Finalizar compra',
    proceed_to_checkout: 'Proceder al pago',
    continue_shopping: 'Seguir comprando',
    copyright: 'Todos los derechos reservados',
    follow_us: 'Síguenos',
    newsletter: 'Boletín',
    subscribe: 'Suscribirse',
    dashboard: 'Panel de control',
    products: 'Productos',
    add_product: 'Agregar producto',
    edit_product: 'Editar producto',
    delete_product: 'Eliminar producto',
    orders_management: 'Gestión de pedidos',
    customers: 'Clientes',
    drivers: 'Conductores',
    analytics: 'Analítica',
    reports: 'Informes',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    update: 'Actualizar',
    create: 'Crear',
    remove: 'Eliminar',
    confirm: 'Confirmar',
    close: 'Cerrar',
  },
  ar: {
    welcome: 'مرحباً',
    shop_now: 'تسوق الآن',
    view_collections: 'عرض المجموعات',
    featured_products: 'منتجات مميزة',
    categories: 'الفئات',
    search: 'بحث',
    cart: 'السلة',
    wishlist: 'قائمة الرغبات',
    account: 'الحساب',
    login: 'تسجيل الدخول',
    register: 'التسجيل',
    logout: 'تسجيل الخروج',
    profile: 'الملف الشخصي',
    orders: 'الطلبات',
    settings: 'الإعدادات',
    help: 'مساعدة',
    contact: 'اتصل بنا',
    about: 'من نحن',
    privacy: 'سياسة الخصوصية',
    terms: 'الشروط والأحكام',
    returns: 'سياسة الإرجاع',
    shipping: 'معلومات الشحن',
    faq: 'الأسئلة الشائعة',
    blog: 'المدونة',
    add_to_cart: 'أضف إلى السلة',
    buy_now: 'اشتر الآن',
    out_of_stock: 'غير متوفر',
    in_stock: 'متوفر',
    low_stock: 'مخزون منخفض',
    price: 'السعر',
    quantity: 'الكمية',
    total: 'المجموع',
    subtotal: 'المجموع الفرعي',
    tax: 'الضريبة',
    shipping_charge: 'رسوم الشحن',
    discount: 'الخصم',
    coupon: 'قسيمة',
    apply_coupon: 'تطبيق القسيمة',
    cart_empty: 'سلتك فارغة',
    cart_total: 'إجمالي السلة',
    checkout: 'إتمام الشراء',
    proceed_to_checkout: 'المتابعة إلى إتمام الشراء',
    continue_shopping: 'مواصلة التسوق',
    copyright: 'جميع الحقوق محفوظة',
    follow_us: 'تابعنا',
    newsletter: 'النشرة الإخبارية',
    subscribe: 'اشتراك',
    dashboard: 'لوحة التحكم',
    products: 'المنتجات',
    add_product: 'إضافة منتج',
    edit_product: 'تعديل المنتج',
    delete_product: 'حذف المنتج',
    orders_management: 'إدارة الطلبات',
    customers: 'العملاء',
    drivers: 'السائقين',
    analytics: 'التحليلات',
    reports: 'التقارير',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    update: 'تحديث',
    create: 'إنشاء',
    remove: 'إزالة',
    confirm: 'تأكيد',
    close: 'إغلاق',
  },
  zh: {
    welcome: '欢迎',
    shop_now: '立即购买',
    view_collections: '查看系列',
    featured_products: '精选产品',
    categories: '分类',
    search: '搜索',
    cart: '购物车',
    wishlist: '心愿单',
    account: '账户',
    login: '登录',
    register: '注册',
    logout: '登出',
    profile: '个人资料',
    orders: '订单',
    settings: '设置',
    help: '帮助',
    contact: '联系我们',
    about: '关于我们',
    privacy: '隐私政策',
    terms: '条款与条件',
    returns: '退货政策',
    shipping: '配送信息',
    faq: '常见问题',
    blog: '博客',
    add_to_cart: '加入购物车',
    buy_now: '立即购买',
    out_of_stock: '缺货',
    in_stock: '有货',
    low_stock: '库存不足',
    price: '价格',
    quantity: '数量',
    total: '总计',
    subtotal: '小计',
    tax: '税费',
    shipping_charge: '运费',
    discount: '折扣',
    coupon: '优惠券',
    apply_coupon: '使用优惠券',
    cart_empty: '您的购物车是空的',
    cart_total: '购物车总计',
    checkout: '结账',
    proceed_to_checkout: '去结账',
    continue_shopping: '继续购物',
    copyright: '版权所有',
    follow_us: '关注我们',
    newsletter: '新闻通讯',
    subscribe: '订阅',
    dashboard: '仪表板',
    products: '产品',
    add_product: '添加产品',
    edit_product: '编辑产品',
    delete_product: '删除产品',
    orders_management: '订单管理',
    customers: '客户',
    drivers: '司机',
    analytics: '分析',
    reports: '报告',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    edit: '编辑',
    update: '更新',
    create: '创建',
    remove: '移除',
    confirm: '确认',
    close: '关闭',
  },
  ja: {
    welcome: 'ようこそ',
    shop_now: '今すぐ買う',
    view_collections: 'コレクションを見る',
    featured_products: '注目商品',
    categories: 'カテゴリー',
    search: '検索',
    cart: 'カート',
    wishlist: 'ウィッシュリスト',
    account: 'アカウント',
    login: 'ログイン',
    register: '登録',
    logout: 'ログアウト',
    profile: 'プロフィール',
    orders: '注文',
    settings: '設定',
    help: 'ヘルプ',
    contact: 'お問い合わせ',
    about: '会社概要',
    privacy: 'プライバシーポリシー',
    terms: '利用規約',
    returns: '返品ポリシー',
    shipping: '配送情報',
    faq: 'よくある質問',
    blog: 'ブログ',
    add_to_cart: 'カートに追加',
    buy_now: '今すぐ購入',
    out_of_stock: '在庫切れ',
    in_stock: '在庫あり',
    low_stock: '在庫わずか',
    price: '価格',
    quantity: '数量',
    total: '合計',
    subtotal: '小計',
    tax: '税金',
    shipping_charge: '送料',
    discount: '割引',
    coupon: 'クーポン',
    apply_coupon: 'クーポンを適用',
    cart_empty: 'カートは空です',
    cart_total: 'カート合計',
    checkout: 'チェックアウト',
    proceed_to_checkout: 'チェックアウトへ進む',
    continue_shopping: '買い物を続ける',
    copyright: '全著作権所有',
    follow_us: 'フォローする',
    newsletter: 'ニュースレター',
    subscribe: '購読する',
    dashboard: 'ダッシュボード',
    products: '商品',
    add_product: '商品を追加',
    edit_product: '商品を編集',
    delete_product: '商品を削除',
    orders_management: '注文管理',
    customers: '顧客',
    drivers: 'ドライバー',
    analytics: '分析',
    reports: 'レポート',
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    edit: '編集',
    update: '更新',
    create: '作成',
    remove: '削除',
    confirm: '確認',
    close: '閉じる',
  },
  ko: {
    welcome: '환영합니다',
    shop_now: '지금 쇼핑하기',
    view_collections: '컬렉션 보기',
    featured_products: '추천 상품',
    categories: '카테고리',
    search: '검색',
    cart: '장바구니',
    wishlist: '위시리스트',
    account: '계정',
    login: '로그인',
    register: '회원가입',
    logout: '로그아웃',
    profile: '프로필',
    orders: '주문',
    settings: '설정',
    help: '도움말',
    contact: '문의하기',
    about: '회사 소개',
    privacy: '개인정보 처리방침',
    terms: '이용약관',
    returns: '반품 정책',
    shipping: '배송 정보',
    faq: '자주 묻는 질문',
    blog: '블로그',
    add_to_cart: '장바구니에 담기',
    buy_now: '지금 구매',
    out_of_stock: '품절',
    in_stock: '재고 있음',
    low_stock: '재고 부족',
    price: '가격',
    quantity: '수량',
    total: '합계',
    subtotal: '소계',
    tax: '세금',
    shipping_charge: '배송료',
    discount: '할인',
    coupon: '쿠폰',
    apply_coupon: '쿠폰 적용',
    cart_empty: '장바구니가 비어 있습니다',
    cart_total: '장바구니 총액',
    checkout: '결제하기',
    proceed_to_checkout: '결제 진행',
    continue_shopping: '쇼핑 계속하기',
    copyright: '모든 권리 보유',
    follow_us: '팔로우',
    newsletter: '뉴스레터',
    subscribe: '구독',
    dashboard: '대시보드',
    products: '상품',
    add_product: '상품 추가',
    edit_product: '상품 수정',
    delete_product: '상품 삭제',
    orders_management: '주문 관리',
    customers: '고객',
    drivers: '운전자',
    analytics: '분석',
    reports: '보고서',
    save: '저장',
    cancel: '취소',
    delete: '삭제',
    edit: '수정',
    update: '업데이트',
    create: '생성',
    remove: '제거',
    confirm: '확인',
    close: '닫기',
  },
};

export const translate = (key, language = 'en', params = {}) => {
  const translation = translations[language]?.[key] || translations['en']?.[key] || key;
  
  // Replace params like {name} in the string
  return translation.replace(/{([^}]+)}/g, (_, param) => params[param] || '');
};

export const t = translate;

export const getSupportedLanguages = () => languages;

export const getLanguage = (code) => {
  return languages.find(l => l.code === code);
};

export const addTranslations = (language, newTranslations) => {
  if (!translations[language]) {
    translations[language] = {};
  }
  Object.assign(translations[language], newTranslations);
};

export default translations;