
'use client';

import React, { createContext, useState, useEffect, useContext, useCallback, useMemo } from 'react';
import toast from 'react-hot-toast';

export const AppContext = createContext();

// ✅ ALL LANGUAGES
export const languages = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
];

// ✅ ALL CURRENCIES
export const currencies = [
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee' },
  { code: 'NPR', symbol: 'रु', name: 'Nepalese Rupee' },
  { code: 'AFN', symbol: '؋', name: 'Afghan Afghani' },
  { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa' },
  { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum' },
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  { code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
];

// ✅ TRANSLATIONS - ALL LANGUAGES
const translations = {
  en: {
    home: 'Home',
    products: 'Products',
    orders: 'Orders',
    track_order: 'Track Order',
    login: 'Login',
    logout: 'Logout',
    wishlist: 'Wishlist',
    filters: 'Filters',
    categories: 'Categories',
    all_categories: 'All Categories',
    price_range: 'Price Range',
    min_price: 'Min Price',
    max_price: 'Max Price',
    sort_by: 'Sort By',
    newest_first: 'Newest First',
    price_low_to_high: 'Price: Low to High',
    price_high_to_low: 'Price: High to Low',
    name_a_to_z: 'Name: A to Z',
    apply_filters: 'Apply Filters',
    clear_all: 'Clear All',
    search_products: 'Search for products...',
    your_profile: 'Your Profile',
    your_orders: 'Your Orders',
    admin_dashboard: 'Admin Dashboard',
    admin: 'Administrator',
    hello: 'Hello',
    sign_in: 'Sign in',
    cart: 'Cart',
    delivering_to: 'Delivering to',
    select_location: 'Select Location',
    currency: 'Currency',
    language: 'Language',
    country: 'Country',
    location: 'Location',
    select_currency: 'Select Currency',
    current: 'Current',
    close: 'Close',
    retry: 'Retry',
    update: 'Update',
    your_location: 'Your Location',
    search_location: 'Search location...',
    auto_detect: 'Auto-detect',
    view_map: 'View Map',
    detecting: 'Detecting...',
    getting_gps: 'Getting GPS...',
    found: 'found',
    detected: 'detected',
    selected: 'selected',
    ip_based: 'IP based - may be inaccurate',
    may_be_inaccurate: 'May be inaccurate',
    enable_gps_tip: 'Enable GPS for accurate location',
    unknown_location: 'Unknown Location',
    search: 'Search',
    all: 'All',
    in_stock: 'In Stock',
    out_of_stock: 'Out of Stock',
    add_to_cart: 'Add to Cart',
    buy_now: 'Buy Now',
    description: 'Description',
    reviews: 'Reviews',
    rating: 'Rating',
    shipping: 'Shipping',
    returns: 'Returns',
    payment: 'Payment',
    order_summary: 'Order Summary',
    subtotal: 'Subtotal',
    discount: 'Discount',
    delivery_charge: 'Delivery Charge',
    proceed_to_checkout: 'Proceed to Checkout',
    continue_shopping: 'Continue Shopping',
    place_order: 'Place Order',
    order_confirmed: 'Order Confirmed',
    order_cancelled: 'Order Cancelled',
    track_your_order: 'Track Your Order',
    order_id: 'Order ID',
    order_date: 'Order Date',
    order_status: 'Order Status',
    delivered: 'Delivered',
    shipped: 'Shipped',
    processing: 'Processing',
    pending: 'Pending',
    cancelled: 'Cancelled',
    refunded: 'Refunded',
    no_products: 'No Products Available',
    shop_description: "India's premium online shopping destination",
    home_title: 'Sombu Store - Premium Products',
    home_description: 'Welcome to Sombu Store',
    hero_title: 'Discover Your Perfect Style',
    hero_subtitle: "We're crafting something amazing!",
    view_collections: 'View Collections',
    shop_now: 'Shop Now',
    explore_products: 'Explore Products',
    free_shipping: 'Free Shipping',
    free_shipping_desc: 'On orders above ₹500',
    secure_payment: 'Secure Payment',
    secure_payment_desc: '100% Secure',
    support: '24/7 Support',
    support_desc: 'Dedicated team',
    easy_returns: 'Easy Returns',
    easy_returns_desc: '7 days return',
    happy_customers: 'Happy Customers',
    brands: 'Brands',
    delivery: 'Delivery*',
    coming_soon: 'Coming Soon',
    soon: 'Soon',
    curating_collection: "We're curating the best collection",
    under_construction: 'Store under construction',
    launching_soon: "Launching soon",
    stay_tuned: 'Stay tuned!',
    progress: 'Progress',
    almost_there: "Almost there!",
     'footer_description': 'Your one-stop destination for all your shopping needs. Quality products, best prices, and fast delivery.',
  'company': 'Company',
  'about_us': 'About Us',
  'careers': 'Careers',
  'press': 'Press',
  'blog': 'Blog',
  'support': 'Support',
  'help_center': 'Help Center',
  'contact_us': 'Contact Us',
  'returns': 'Returns',
  'shipping_info': 'Shipping Info',
  'faqs': 'FAQs',
  'track_order': 'Track Order',
  'legal': 'Legal',
  'privacy_policy': 'Privacy Policy',
  'terms_of_service': 'Terms of Service',
  'cookie_policy': 'Cookie Policy',
  'gdpr': 'GDPR',
  'disclaimer': 'Disclaimer',
  'account': 'Account',
  'my_account': 'My Account',
  'orders': 'Orders',
  'wishlist': 'Wishlist',
  'cart': 'Cart',
  'settings': 'Settings',
  'all_rights_reserved': 'All rights reserved.',
    current_language: 'Current Language',
    current_currency: 'Current Currency',
    select_language: 'Select Language',
    change_language: 'Change Language',
    all_languages: 'All Languages',
    tamil: 'Tamil',
    hindi: 'Hindi',
    telugu: 'Telugu',
    malayalam: 'Malayalam',
    kannada: 'Kannada',
    bengali: 'Bengali',
    marathi: 'Marathi',
    gujarati: 'Gujarati',
    punjabi: 'Punjabi',
    english: 'English',
  },
  ta: {
    home: 'முகப்பு',
    products: 'தயாரிப்புகள்',
    orders: 'ஆர்டர்கள்',
    track_order: 'ஆர்டரை கண்காணி',
    login: 'உள்நுழை',
    logout: 'வெளியேறு',
    wishlist: 'விருப்ப பட்டியல்',
    filters: 'வடிப்பான்கள்',
    categories: 'வகைகள்',
    all_categories: 'அனைத்து வகைகளும்',
    price_range: 'விலை வரம்பு',
    min_price: 'குறைந்தபட்ச விலை',
    max_price: 'அதிகபட்ச விலை',
    sort_by: 'வரிசைப்படுத்து',
    newest_first: 'புதியவை முதலில்',
    price_low_to_high: 'குறைந்த விலையில் இருந்து உயர்',
    price_high_to_low: 'உயர் விலையில் இருந்து குறைந்த',
    name_a_to_z: 'பெயர் A முதல் Z',
    apply_filters: 'வடிப்பான்களை பயன்படுத்து',
    clear_all: 'அனைத்து வடிப்பான்களையும் அழி',
    search_products: 'தயாரிப்புகளை தேடுங்கள்...',
    your_profile: 'உங்கள் சுயவிவரம்',
    your_orders: 'உங்கள் ஆர்டர்கள்',
    admin_dashboard: 'நிர்வாகி கட்டுப்பாட்டு பலகை',
    admin: 'நிர்வாகி',
    hello: 'வணக்கம்',
    sign_in: 'உள்நுழையவும்',
    cart: 'கார்ட்',
    delivering_to: 'டெலிவரி செய்யப்படுகிறது',
    select_location: 'இருப்பிடத்தை தேர்ந்தெடுக்கவும்',
    currency: 'நாணயம்',
    language: 'மொழி',
    country: 'நாடு',
    location: 'இருப்பிடம்',
    select_currency: 'நாணயத்தை தேர்ந்தெடுக்கவும்',
    current: 'தற்போதைய',
    close: 'மூடு',
    retry: 'மீண்டும் முயற்சி செய்',
    update: 'புதுப்பி',
    your_location: 'உங்கள் இருப்பிடம்',
    search_location: 'இருப்பிடத்தை தேடு...',
    auto_detect: 'தானாக கண்டறி',
    view_map: 'வரைபடத்தை காண்க',
    detecting: 'கண்டறிகிறது...',
    getting_gps: 'GPS பெறுகிறது...',
    found: 'கண்டுபிடிக்கப்பட்டது',
    detected: 'கண்டறியப்பட்டது',
    selected: 'தேர்ந்தெடுக்கப்பட்டது',
    ip_based: 'IP அடிப்படையில் - தவறாக இருக்கலாம்',
    may_be_inaccurate: 'தவறாக இருக்கலாம்',
    enable_gps_tip: 'துல்லியமான இருப்பிடத்திற்கு GPS ஐ இயக்கவும்',
    unknown_location: 'அறியப்படாத இருப்பிடம்',
    search: 'தேடு',
    all: 'அனைத்தும்',
    in_stock: 'கையிருப்பில் உள்ளது',
    out_of_stock: 'கையிருப்பில் இல்லை',
    add_to_cart: 'கார்டில் சேர்',
    buy_now: 'இப்போது வாங்க',
    description: 'விளக்கம்',
    reviews: 'விமர்சனங்கள்',
    rating: 'மதிப்பீடு',
    shipping: 'கப்பல்',
    returns: 'திரும்பப் பெறுதல்',
    payment: 'கட்டணம்',
    order_summary: 'ஆர்டர் சுருக்கம்',
    subtotal: 'துணை மொத்தம்',
    discount: 'தள்ளுபடி',
    delivery_charge: 'டெலிவரி கட்டணம்',
    proceed_to_checkout: 'செலுத்துவதற்கு செல்லவும்',
    continue_shopping: 'தொடர்ந்து ஷாப்பிங் செய்யுங்கள்',
    place_order: 'ஆர்டர் செய்யுங்கள்',
    order_confirmed: 'ஆர்டர் உறுதி செய்யப்பட்டது',
    order_cancelled: 'ஆர்டர் ரத்து செய்யப்பட்டது',
    track_your_order: 'உங்கள் ஆர்டரை கண்காணிக்கவும்',
    order_id: 'ஆர்டர் ID',
    order_date: 'ஆர்டர் தேதி',
    order_status: 'ஆர்டர் நிலை',
    delivered: 'டெலிவரி செய்யப்பட்டது',
    shipped: 'அனுப்பப்பட்டது',
    processing: 'செயலாக்கம்',
    pending: 'நிலுவையில்',
    cancelled: 'ரத்து செய்யப்பட்டது',
    refunded: 'பணம் திருப்பி வழங்கப்பட்டது',
    no_products: 'தயாரிப்புகள் எதுவும் இல்லை',
    shop_description: "இந்தியாவின் பிரீமியம் ஆன்லைன் ஷாப்பிங் இடம்",
    home_title: 'Sombu ஸ்டோர் - பிரீமியம் தயாரிப்புகள்',
    home_description: 'Sombu ஸ்டோருக்கு வரவேற்கிறோம்',
    hero_title: 'உங்களின் சிறந்த பாணியை கண்டறியுங்கள்',
    hero_subtitle: "நாங்கள் அற்புதமான ஒன்றை உருவாக்குகிறோம்!",
    view_collections: 'சேகரிப்புகளைக் காண்க',
    shop_now: 'இப்போது வாங்க',
    explore_products: 'தயாரிப்புகளை ஆராயுங்கள்',
    free_shipping: 'இலவச டெலிவரி',
    free_shipping_desc: '₹500 க்கு மேல் ஆர்டர்களில்',
    secure_payment: 'பாதுகாப்பான கட்டணம்',
    secure_payment_desc: '100% பாதுகாப்பானது',
    support: '24/7 ஆதரவு',
    support_desc: 'அர்ப்பணிப்பு குழு',
    easy_returns: 'எளிதான ரிட்டர்ன்',
    easy_returns_desc: '7 நாட்கள் ரிட்டர்ன்',
    happy_customers: 'மகிழ்ச்சியான வாடிக்கையாளர்கள்',
    brands: 'பிராண்டுகள்',
    delivery: 'டெலிவரி*',
    coming_soon: 'விரைவில் வருகிறது',
    soon: 'விரைவில்',
    curating_collection: "சிறந்த சேகரிப்புகளை தயாரித்து வருகிறோம்",
    under_construction: 'ஸ்டோர் கட்டுமானத்தில் உள்ளது',
    launching_soon: "விரைவில் திறக்கிறோம்",
    stay_tuned: 'காத்திருங்கள்!',
    progress: 'முன்னேற்றம்',
    almost_there: "கிட்டத்தட்ட முடிந்துவிட்டது!",
    'footer_description': 'உங்கள் அனைத்து ஷாப்பிங் தேவைகளுக்கும் ஒரே இடம். தரமான பொருட்கள், சிறந்த விலைகள், மற்றும் வேகமான டெலிவரி.',
  'company': 'நிறுவனம்',
  'about_us': 'எங்களைப் பற்றி',
  'careers': 'வேலைவாய்ப்புகள்',
  'press': 'பத்திரிகை',
  'blog': 'வலைப்பதிவு',
  'support': 'ஆதரவு',
  'help_center': 'உதவி மையம்',
  'contact_us': 'எங்களை தொடர்பு கொள்ள',
  'returns': 'திருப்பி அனுப்புதல்',
  'shipping_info': 'விநியோக தகவல்கள்',
  'faqs': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
  'track_order': 'ஆர்டரை கண்காணி',
  'legal': 'சட்டப்பூர்வம்',
  'privacy_policy': 'தனியுரிமை கொள்கை',
  'terms_of_service': 'சேவை விதிமுறைகள்',
  'cookie_policy': 'குக்கீ கொள்கை',
  'gdpr': 'GDPR',
  'disclaimer': 'மறுப்பு',
  'account': 'கணக்கு',
  'my_account': 'என் கணக்கு',
  'orders': 'ஆர்டர்கள்',
  'wishlist': 'விருப்பப்பட்டியல்',
  'cart': 'கார்ட்',
  'settings': 'அமைப்புகள்',
  'all_rights_reserved': 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    current_language: 'தற்போதைய மொழி',
    current_currency: 'தற்போதைய நாணயம்',
    select_language: 'மொழியை தேர்ந்தெடுக்கவும்',
    change_language: 'மொழியை மாற்று',
    all_languages: 'அனைத்து மொழிகளும்',
    tamil: 'தமிழ்',
    hindi: 'இந்தி',
    telugu: 'தெலுங்கு',
    malayalam: 'மலையாளம்',
    kannada: 'கன்னடம்',
    bengali: 'வங்காளம்',
    marathi: 'மராத்தி',
    gujarati: 'குஜராத்தி',
    punjabi: 'பஞ்சாபி',
    english: 'ஆங்கிலம்',
  },
  hi: {
    home: 'होम',
    products: 'उत्पाद',
    orders: 'ऑर्डर',
    track_order: 'ट्रैक ऑर्डर',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    wishlist: 'विशलिस्ट',
    filters: 'फ़िल्टर',
    categories: 'श्रेणियाँ',
    all_categories: 'सभी श्रेणियाँ',
    price_range: 'मूल्य सीमा',
    min_price: 'न्यूनतम मूल्य',
    max_price: 'अधिकतम मूल्य',
    sort_by: 'क्रमबद्ध करें',
    newest_first: 'नवीनतम पहले',
    price_low_to_high: 'कम से ज्यादा कीमत',
    price_high_to_low: 'ज्यादा से कम कीमत',
    name_a_to_z: 'नाम A से Z',
    apply_filters: 'फ़िल्टर लागू करें',
    clear_all: 'सभी फ़िल्टर साफ़ करें',
    search_products: 'उत्पाद खोजें...',
    your_profile: 'आपकी प्रोफ़ाइल',
    your_orders: 'आपके ऑर्डर',
    admin_dashboard: 'एडमिन डैशबोर्ड',
    admin: 'प्रशासक',
    hello: 'नमस्ते',
    sign_in: 'साइन इन करें',
    cart: 'कार्ट',
    delivering_to: 'डिलीवरी हो रही है',
    select_location: 'स्थान चुनें',
    currency: 'मुद्रा',
    language: 'भाषा',
    country: 'देश',
    location: 'स्थान',
    select_currency: 'मुद्रा चुनें',
    current: 'वर्तमान',
    close: 'बंद करें',
    retry: 'पुनः प्रयास करें',
    update: 'अपडेट करें',
    your_location: 'आपका स्थान',
    search_location: 'स्थान खोजें...',
    auto_detect: 'स्वतः पहचानें',
    view_map: 'मानचित्र देखें',
    detecting: 'पहचान हो रही है...',
    getting_gps: 'GPS प्राप्त हो रहा है...',
    found: 'मिला',
    detected: 'पहचाना गया',
    selected: 'चुना गया',
    ip_based: 'IP आधारित - अशुद्ध हो सकता है',
    may_be_inaccurate: 'अशुद्ध हो सकता है',
    enable_gps_tip: 'सटीक स्थान के लिए GPS सक्षम करें',
    unknown_location: 'अज्ञात स्थान',
    search: 'खोजें',
    all: 'सभी',
    in_stock: 'स्टॉक में',
    out_of_stock: 'स्टॉक से बाहर',
    add_to_cart: 'कार्ट में डालें',
    buy_now: 'अभी खरीदें',
    description: 'विवरण',
    reviews: 'समीक्षाएँ',
    rating: 'रेटिंग',
    shipping: 'शिपिंग',
    returns: 'रिटर्न',
    payment: 'भुगतान',
    order_summary: 'ऑर्डर सारांश',
    subtotal: 'उप-योग',
    discount: 'छूट',
    delivery_charge: 'डिलीवरी शुल्क',
    proceed_to_checkout: 'चेकआउट पर जाएं',
    continue_shopping: 'खरीदारी जारी रखें',
    place_order: 'ऑर्डर दें',
    order_confirmed: 'ऑर्डर पुष्टि हुई',
    order_cancelled: 'ऑर्डर रद्द',
    track_your_order: 'अपना ऑर्डर ट्रैक करें',
    order_id: 'ऑर्डर ID',
    order_date: 'ऑर्डर तिथि',
    order_status: 'ऑर्डर स्थिति',
    delivered: 'डिलीवर हो गया',
    shipped: 'शिप हो गया',
    processing: 'प्रोसेस हो रहा है',
    pending: 'लंबित',
    cancelled: 'रद्द',
    refunded: 'रिफंड हुआ',
    no_products: 'कोई उत्पाद उपलब्ध नहीं',
    shop_description: "भारत का प्रीमियम ऑनलाइन शॉपिंग गंतव्य",
    home_title: 'Sombu स्टोर - प्रीमियम उत्पाद',
    home_description: 'Sombu स्टोर में आपका स्वागत है',
    hero_title: 'खोजें अपनी परफेक्ट स्टाइल',
    hero_subtitle: "हम कुछ अद्भुत बना रहे हैं!",
    view_collections: 'कलेक्शन देखें',
    shop_now: 'अभी खरीदें',
    explore_products: 'उत्पाद खोजें',
    free_shipping: 'मुफ्त शिपिंग',
    free_shipping_desc: '₹500 से अधिक के ऑर्डर पर',
    secure_payment: 'सुरक्षित भुगतान',
    secure_payment_desc: '100% सुरक्षित',
    support: '24/7 सहायता',
    support_desc: 'समर्पित टीम',
    easy_returns: 'आसान रिटर्न',
    easy_returns_desc: '7 दिन रिटर्न',
    happy_customers: 'खुश ग्राहक',
    brands: 'ब्रांड्स',
    delivery: 'डिलीवरी*',
    coming_soon: 'जल्द आ रहा है',
    soon: 'जल्द',
    curating_collection: "हम सबसे अच्छा कलेक्शन तैयार कर रहे हैं",
    under_construction: 'स्टोर निर्माणाधीन है',
    launching_soon: "हम जल्द ही लॉन्च कर रहे हैं",
    stay_tuned: 'बने रहें!',
    progress: 'प्रगति',
    almost_there: "बस कुछ ही दूरी पर!",
     'footer_description': 'आपकी सभी शॉपिंग ज़रूरतों के लिए एक-स्टॉप गंतव्य। गुणवत्ता वाले उत्पाद, बेस्ट कीमतें, और तेज़ डिलीवरी।',
  'company': 'कंपनी',
  'about_us': 'हमारे बारे में',
  'careers': 'करियर',
  'press': 'प्रेस',
  'blog': 'ब्लॉग',
  'support': 'सहायता',
  'help_center': 'सहायता केंद्र',
  'contact_us': 'संपर्क करें',
  'returns': 'वापसी',
  'shipping_info': 'शिपिंग जानकारी',
  'faqs': 'सामान्य प्रश्न',
  'track_order': 'ऑर्डर ट्रैक करें',
  'legal': 'कानूनी',
  'privacy_policy': 'गोपनीयता नीति',
  'terms_of_service': 'सेवा की शर्तें',
  'cookie_policy': 'कुकी नीति',
  'gdpr': 'GDPR',
  'disclaimer': 'अस्वीकरण',
  'account': 'खाता',
  'my_account': 'मेरा खाता',
  'orders': 'ऑर्डर',
  'wishlist': 'विशलिस्ट',
  'cart': 'कार्ट',
  'settings': 'सेटिंग्स',
  'all_rights_reserved': 'सभी अधिकार सुरक्षित।',
    current_language: 'वर्तमान भाषा',
    current_currency: 'वर्तमान मुद्रा',
    select_language: 'भाषा चुनें',
    change_language: 'भाषा बदलें',
    all_languages: 'सभी भाषाएँ',
    tamil: 'तमिल',
    hindi: 'हिंदी',
    telugu: 'तेलुगु',
    malayalam: 'मलयालम',
    kannada: 'कन्नड़',
    bengali: 'बांग्ला',
    marathi: 'मराठी',
    gujarati: 'गुजराती',
    punjabi: 'पंजाबी',
    english: 'अंग्रेज़ी',
  },
  te: {
    home: 'హోమ్',
    products: 'ఉత్పత్తులు',
    orders: 'ఆర్డర్లు',
    track_order: 'ఆర్డర్ ట్రాక్ చేయండి',
    login: 'లాగిన్',
    logout: 'లాగౌట్',
    wishlist: 'విశ్లిస్ట్',
    filters: 'ఫిల్టర్లు',
    categories: 'వర్గాలు',
    all_categories: 'అన్ని వర్గాలు',
    price_range: 'ధర పరిధి',
    min_price: 'కనీస ధర',
    max_price: 'గరిష్ట ధర',
    sort_by: 'క్రమీకరించు',
    newest_first: 'కొత్తవి మొదట',
    price_low_to_high: 'తక్కువ నుండి ఎక్కువ ధర',
    price_high_to_low: 'ఎక్కువ నుండి తక్కువ ధర',
    name_a_to_z: 'పేరు A నుండి Z',
    apply_filters: 'ఫిల్టర్లు వర్తించు',
    clear_all: 'అన్నీ క్లియర్ చేయి',
    search_products: 'ఉత్పత్తుల కోసం శోధించండి...',
    your_profile: 'మీ ప్రొఫైల్',
    your_orders: 'మీ ఆర్డర్లు',
    admin_dashboard: 'అడ్మిన్ డాష్‌బోర్డ్',
    admin: 'నిర్వాహకుడు',
    hello: 'నమస్కారం',
    sign_in: 'సైన్ ఇన్ చేయండి',
    cart: 'కార్ట్',
    delivering_to: 'డెలివరీ చేస్తున్నాము',
    select_location: 'స్థానాన్ని ఎంచుకోండి',
    currency: 'కరెన్సీ',
    language: 'భాష',
    country: 'దేశం',
    location: 'స్థానం',
    select_currency: 'కరెన్సీని ఎంచుకోండి',
    current: 'ప్రస్తుత',
    close: 'మూసివేయి',
    retry: 'మళ్ళీ ప్రయత్నించు',
    update: 'నవీకరించు',
    your_location: 'మీ స్థానం',
    search_location: 'స్థానం శోధించండి...',
    auto_detect: 'స్వయంచాలకంగా గుర్తించు',
    view_map: 'మ్యాప్ చూడండి',
    detecting: 'గుర్తిస్తోంది...',
    getting_gps: 'GPS పొందుతోంది...',
    found: 'కనుగొనబడింది',
    detected: 'గుర్తించబడింది',
    selected: 'ఎంచుకోబడింది',
    ip_based: 'IP ఆధారిత - సరికాదు',
    may_be_inaccurate: 'సరికాదు',
    enable_gps_tip: 'ఖచ్చితమైన స్థానం కోసం GPS ని ప్రారంభించండి',
    unknown_location: 'తెలియని స్థానం',
    search: 'శోధించు',
    all: 'అన్నీ',
    in_stock: 'స్టాక్‌లో ఉంది',
    out_of_stock: 'స్టాక్‌లో లేదు',
    add_to_cart: 'కార్ట్‌లో చేర్చు',
    buy_now: 'ఇప్పుడే కొనుగోలు చేయి',
    description: 'వివరణ',
    reviews: 'సమీక్షలు',
    rating: 'రేటింగ్',
    shipping: 'షిప్పింగ్',
    returns: 'తిరిగి ఇవ్వడం',
    payment: 'చెల్లింపు',
    order_summary: 'ఆర్డర్ సారాంశం',
    subtotal: 'మొత్తం',
    discount: 'డిస్కౌంట్',
    delivery_charge: 'డెలివరీ ఛార్జ్',
    proceed_to_checkout: 'చెక్‌అవుట్‌కు వెళ్ళు',
    continue_shopping: 'షాపింగ్ కొనసాగించు',
    place_order: 'ఆర్డర్ ఇవ్వు',
    order_confirmed: 'ఆర్డర్ ధృవీకరించబడింది',
    order_cancelled: 'ఆర్డర్ రద్దు చేయబడింది',
    track_your_order: 'మీ ఆర్డర్ ట్రాక్ చేయండి',
    order_id: 'ఆర్డర్ ID',
    order_date: 'ఆర్డర్ తేదీ',
    order_status: 'ఆర్డర్ స్థితి',
    delivered: 'డెలివరీ చేయబడింది',
    shipped: 'షిప్ చేయబడింది',
    processing: 'ప్రాసెస్ చేస్తోంది',
    pending: 'పెండింగ్',
    cancelled: 'రద్దు చేయబడింది',
    refunded: 'రీఫండ్ చేయబడింది',
    no_products: 'ఉత్పత్తులు అందుబాటులో లేవు',
    shop_description: "భారతదేశ ప్రీమియం ఆన్‌లైన్ షాపింగ్ గమ్యం",
    home_title: 'Sombu స్టోర్ - ప్రీమియం ఉత్పత్తులు',
    home_description: 'Sombu స్టోర్కు స్వాగతం',
    hero_title: 'మీ స్టైల్ కనుగొనండి',
    hero_subtitle: "మేము అద్భుతమైనదాన్ని సృష్టిస్తున్నాము!",
    view_collections: 'కలెక్షన్స్ చూడండి',
    shop_now: 'ఇప్పుడే కొనండి',
    explore_products: 'ఉత్పత్తులను అన్వేషించండి',
    free_shipping: 'ఉచిత షిప్పింగ్',
    free_shipping_desc: '₹500 పైన ఆర్డర్లకు',
    secure_payment: 'సురక్షిత చెల్లింపు',
    secure_payment_desc: '100% సురక్షితం',
    support: '24/7 మద్దతు',
    support_desc: 'అంకిత బృందం',
    easy_returns: 'సులభ రిటర్న్స్',
    easy_returns_desc: '7 రోజుల రిటర్న్',
    happy_customers: 'సంతోషకరమైన కస్టమర్లు',
    brands: 'బ్రాండ్లు',
    delivery: 'డెలివరీ*',
    coming_soon: 'త్వరలో వస్తుంది',
    soon: 'త్వరలో',
    curating_collection: "మేము ఉత్తమ కలెక్షన్ సిద్ధం చేస్తున్నాము",
    under_construction: 'స్టోర్ నిర్మాణంలో ఉంది',
    launching_soon: "త్వరలో ప్రారంభం",
    stay_tuned: 'వేచి ఉండండి!',
    progress: 'పురోగతి',
    almost_there: "ఇంకా కొంచెం!",
    'footer_description': 'మీ అన్ని షాపింగ్ అవసరాలకు వన్-స్టాప్ గమ్యం. నాణ్యమైన ఉత్పత్తులు, ఉత్తమ ధరలు, మరియు వేగవంతమైన డెలివరీ.',
  'company': 'కంపెనీ',
  'about_us': 'మా గురించి',
  'careers': 'ఉద్యోగాలు',
  'press': 'ప్రెస్',
  'blog': 'బ్లాగ్',
  'support': 'మద్దతు',
  'help_center': 'సహాయ కేంద్రం',
  'contact_us': 'మమ్మల్ని సంప్రదించండి',
  'returns': 'తిరిగి ఇవ్వడం',
  'shipping_info': 'షిప్పింగ్ సమాచారం',
  'faqs': 'తరచుగా అడిగే ప్రశ్నలు',
  'track_order': 'ఆర్డర్ ట్రాక్ చేయండి',
  'legal': 'చట్టపరమైన',
  'privacy_policy': 'గోప్యతా విధానం',
  'terms_of_service': 'సేవా నిబంధనలు',
  'cookie_policy': 'కుకీ విధానం',
  'gdpr': 'GDPR',
  'disclaimer': 'హెచ్చరిక',
  'account': 'ఖాతా',
  'my_account': 'నా ఖాతా',
  'orders': 'ఆర్డర్లు',
  'wishlist': 'విశ్లిస్ట్',
  'cart': 'కార్ట్',
  'settings': 'సెట్టింగ్స్',
  'all_rights_reserved': 'అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.',
    current_language: 'ప్రస్తుత భాష',
    current_currency: 'ప్రస్తుత కరెన్సీ',
    select_language: 'భాష ఎంచుకోండి',
    change_language: 'భాష మార్చు',
    all_languages: 'అన్ని భాషలు',
    tamil: 'తమిళం',
    hindi: 'హిందీ',
    telugu: 'తెలుగు',
    malayalam: 'మలయాళం',
    kannada: 'కన్నడ',
    bengali: 'బెంగాలీ',
    marathi: 'మరాఠీ',
    gujarati: 'గుజరాతీ',
    punjabi: 'పంజాబీ',
    english: 'ఇంగ్లీష్',
  },
  ml: {
    home: 'ഹോം',
    products: 'ഉൽപ്പന്നങ്ങൾ',
    orders: 'ഓർഡറുകൾ',
    track_order: 'ഓർഡർ ട്രാക്ക് ചെയ്യുക',
    login: 'ലോഗിൻ',
    logout: 'ലോഗൗട്ട്',
    wishlist: 'വിഷ്ലിസ്റ്റ്',
    filters: 'ഫിൽട്ടറുകൾ',
    categories: 'വിഭാഗങ്ങൾ',
    all_categories: 'എല്ലാ വിഭാഗങ്ങളും',
    price_range: 'വില പരിധി',
    min_price: 'കുറഞ്ഞ വില',
    max_price: 'കൂടിയ വില',
    sort_by: 'ക്രമീകരിക്കുക',
    newest_first: 'പുതിയത് ആദ്യം',
    price_low_to_high: 'വില: കുറഞ്ഞത് മുതൽ കൂടിയത് വരെ',
    price_high_to_low: 'വില: കൂടിയത് മുതൽ കുറഞ്ഞത് വരെ',
    name_a_to_z: 'പേര്: A മുതൽ Z വരെ',
    apply_filters: 'ഫിൽട്ടറുകൾ പ്രയോഗിക്കുക',
    clear_all: 'എല്ലാം മായ്ക്കുക',
    search_products: 'ഉൽപ്പന്നങ്ങൾക്കായി തിരയുക...',
    your_profile: 'നിങ്ങളുടെ പ്രൊഫൈൽ',
    your_orders: 'നിങ്ങളുടെ ഓർഡറുകൾ',
    admin_dashboard: 'അഡ്മിൻ ഡാഷ്ബോർഡ്',
    admin: 'അഡ്മിനിസ്ട്രേറ്റർ',
    hello: 'നമസ്കാരം',
    sign_in: 'സൈൻ ഇൻ ചെയ്യുക',
    cart: 'കാർട്ട്',
    delivering_to: 'ഡെലിവറി ചെയ്യുന്നത്',
    select_location: 'സ്ഥാനം തിരഞ്ഞെടുക്കുക',
    currency: 'കറൻസി',
    language: 'ഭാഷ',
    country: 'രാജ്യം',
    location: 'സ്ഥാനം',
    select_currency: 'കറൻസി തിരഞ്ഞെടുക്കുക',
    current: 'നിലവിലുള്ളത്',
    close: 'അടയ്ക്കുക',
    retry: 'വീണ്ടും ശ്രമിക്കുക',
    update: 'അപ്ഡേറ്റ് ചെയ്യുക',
    your_location: 'നിങ്ങളുടെ സ്ഥാനം',
    search_location: 'സ്ഥാനം തിരയുക...',
    auto_detect: 'സ്വയം കണ്ടെത്തുക',
    view_map: 'മാപ്പ് കാണുക',
    detecting: 'കണ്ടെത്തുന്നു...',
    getting_gps: 'GPS ലഭിക്കുന്നു...',
    found: 'കണ്ടെത്തി',
    detected: 'കണ്ടെത്തി',
    selected: 'തിരഞ്ഞെടുത്തു',
    ip_based: 'IP അടിസ്ഥാനമാക്കി - കൃത്യമല്ലായിരിക്കാം',
    may_be_inaccurate: 'കൃത്യമല്ലായിരിക്കാം',
    enable_gps_tip: 'കൃത്യമായ സ്ഥാനത്തിന് GPS പ്രവർത്തനക്ഷമമാക്കുക',
    unknown_location: 'അജ്ഞാത സ്ഥാനം',
    search: 'തിരയുക',
    all: 'എല്ലാം',
    in_stock: 'സ്റ്റോക്കിൽ ഉണ്ട്',
    out_of_stock: 'സ്റ്റോക്കിൽ ഇല്ല',
    add_to_cart: 'കാർട്ടിലേക്ക് ചേർക്കുക',
    buy_now: 'ഇപ്പോൾ വാങ്ങുക',
    description: 'വിവരണം',
    reviews: 'അവലോകനങ്ങൾ',
    rating: 'റേറ്റിംഗ്',
    shipping: 'ഷിപ്പിംഗ്',
    returns: 'റിട്ടേൺസ്',
    payment: 'പേയ്മെന്റ്',
    order_summary: 'ഓർഡർ സംഗ്രഹം',
    subtotal: 'ഉപമൊത്തം',
    discount: 'കിഴിവ്',
    delivery_charge: 'ഡെലിവറി ചാർജ്',
    proceed_to_checkout: 'ചെക്ക്ഔട്ടിലേക്ക് പോകുക',
    continue_shopping: 'ഷോപ്പിംഗ് തുടരുക',
    place_order: 'ഓർഡർ നൽകുക',
    order_confirmed: 'ഓർഡർ സ്ഥിരീകരിച്ചു',
    order_cancelled: 'ഓർഡർ റദ്ദാക്കി',
    track_your_order: 'നിങ്ങളുടെ ഓർഡർ ട്രാക്ക് ചെയ്യുക',
    order_id: 'ഓർഡർ ID',
    order_date: 'ഓർഡർ തീയതി',
    order_status: 'ഓർഡർ നില',
    delivered: 'ഡെലിവർ ചെയ്തു',
    shipped: 'ഷിപ്പ് ചെയ്തു',
    processing: 'പ്രോസസ്സ് ചെയ്യുന്നു',
    pending: 'പെൻഡിംഗ്',
    cancelled: 'റദ്ദാക്കി',
    refunded: 'റീഫണ്ട് ചെയ്തു',
    no_products: 'ഉൽപ്പന്നങ്ങൾ ലഭ്യമല്ല',
    shop_description: "ഇന്ത്യയുടെ പ്രീമിയം ഓൺലൈൻ ഷോപ്പിംഗ് ലക്ഷ്യസ്ഥാനം",
    home_title: 'Sombu സ്റ്റോർ - പ്രീമിയം ഉൽപ്പന്നങ്ങൾ',
    home_description: 'Sombu സ്റ്റോറിലേക്ക് സ്വാഗതം',
    hero_title: 'നിങ്ങളുടെ സ്റ്റൈൽ കണ്ടെത്തുക',
    hero_subtitle: "ഞങ്ങൾ അതിശയകരമായ എന്തോ ഒന്ന് നിർമ്മിക്കുകയാണ്!",
    view_collections: 'കളക്ഷനുകൾ കാണുക',
    shop_now: 'ഇപ്പോൾ വാങ്ങുക',
    explore_products: 'ഉൽപ്പന്നങ്ങൾ പര്യവേക്ഷണം ചെയ്യുക',
    free_shipping: 'സൗജന്യ ഷിപ്പിംഗ്',
    free_shipping_desc: '₹500 ന് മുകളിലുള്ള ഓർഡറുകൾക്ക്',
    secure_payment: 'സുരക്ഷിത പേയ്മെന്റ്',
    secure_payment_desc: '100% സുരക്ഷിതം',
    support: '24/7 പിന്തുണ',
    support_desc: 'സമർപ്പിത ടീം',
    easy_returns: 'എളുപ്പ റിട്ടേൺസ്',
    easy_returns_desc: '7 ദിവസം റിട്ടേൺ',
    happy_customers: 'സന്തുഷ്ടരായ ഉപഭോക്താക്കൾ',
    brands: 'ബ്രാൻഡുകൾ',
    delivery: 'ഡെലിവറി*',
    coming_soon: 'ഉടൻ വരുന്നു',
    soon: 'ഉടൻ',
    curating_collection: "ഞങ്ങൾ മികച്ച കളക്ഷൻ തയ്യാറാക്കുന്നു",
    under_construction: 'സ്റ്റോർ നിർമ്മാണത്തിലാണ്',
    launching_soon: "ഉടൻ ലോഞ്ച് ചെയ്യുന്നു",
    stay_tuned: 'കാത്തിരിക്കുക!',
    progress: 'പുരോഗതി',
    almost_there: "ഏകദേശം പൂർത്തിയായി!",
     'footer_description': 'നിങ്ങളുടെ എല്ലാ ഷോപ്പിംഗ് ആവശ്യങ്ങൾക്കും ഒരു സ്ഥലം. ഗുണമേന്മയുള്ള ഉൽപ്പന്നങ്ങൾ, മികച്ച വിലകൾ, വേഗത്തിലുള്ള ഡെലിവറി.',
  'company': 'കമ്പനി',
  'about_us': 'ഞങ്ങളെക്കുറിച്ച്',
  'careers': 'തൊഴിലവസരങ്ങൾ',
  'press': 'പ്രസ്സ്',
  'blog': 'ബ്ലോഗ്',
  'support': 'പിന്തുണ',
  'help_center': 'സഹായ കേന്ദ്രം',
  'contact_us': 'ഞങ്ങളെ ബന്ധപ്പെടുക',
  'returns': 'തിരിച്ചയയ്ക്കൽ',
  'shipping_info': 'ഷിപ്പിംഗ് വിവരങ്ങൾ',
  'faqs': 'പതിവ് ചോദ്യങ്ങൾ',
  'track_order': 'ഓർഡർ ട്രാക്ക് ചെയ്യുക',
  'legal': 'നിയമപരമായ',
  'privacy_policy': 'സ്വകാര്യതാ നയം',
  'terms_of_service': 'സേവന നിബന്ധനകൾ',
  'cookie_policy': 'കുക്കി നയം',
  'gdpr': 'GDPR',
  'disclaimer': 'മുന്നറിയിപ്പ്',
  'account': 'അക്കൗണ്ട്',
  'my_account': 'എന്റെ അക്കൗണ്ട്',
  'orders': 'ഓർഡറുകൾ',
  'wishlist': 'വിഷ്ലിസ്റ്റ്',
  'cart': 'കാർട്ട്',
  'settings': 'ക്രമീകരണങ്ങൾ',
  'all_rights_reserved': 'എല്ലാ അവകാശങ്ങളും നീക്കിവച്ചിരിക്കുന്നു.',
    current_language: 'നിലവിലെ ഭാഷ',
    current_currency: 'നിലവിലെ കറൻസി',
    select_language: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    change_language: 'ഭാഷ മാറ്റുക',
    all_languages: 'എല്ലാ ഭാഷകളും',
    tamil: 'തമിഴ്',
    hindi: 'ഹിന്ദി',
    telugu: 'തെലുങ്ക്',
    malayalam: 'മലയാളം',
    kannada: 'കന്നഡ',
    bengali: 'ബംഗാളി',
    marathi: 'മറാത്തി',
    gujarati: 'ഗുജറാത്തി',
    punjabi: 'പഞ്ചാബി',
    english: 'ഇംഗ്ലീഷ്',
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    products: 'ಉತ್ಪನ್ನಗಳು',
    orders: 'ಆರ್ಡರ್ಗಳು',
    track_order: 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    login: 'ಲಾಗಿನ್',
    logout: 'ಲಾಗೌಟ್',
    wishlist: 'ವಿಶ್ಲಿಸ್ಟ್',
    filters: 'ಫಿಲ್ಟರ್ಗಳು',
    categories: 'ವರ್ಗಗಳು',
    all_categories: 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
    price_range: 'ಬೆಲೆ ವ್ಯಾಪ್ತಿ',
    min_price: 'ಕನಿಷ್ಠ ಬೆಲೆ',
    max_price: 'ಗರಿಷ್ಠ ಬೆಲೆ',
    sort_by: 'ವಿಂಗಡಿಸು',
    newest_first: 'ಹೊಸದು ಮೊದಲು',
    price_low_to_high: 'ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚಿಗೆ ಬೆಲೆ',
    price_high_to_low: 'ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆಗೆ ಬೆಲೆ',
    name_a_to_z: 'ಹೆಸರು A ನಿಂದ Z',
    apply_filters: 'ಫಿಲ್ಟರ್ಗಳನ್ನು ಅನ್ವಯಿಸಿ',
    clear_all: 'ಎಲ್ಲವನ್ನೂ ಅಳಿಸಿ',
    search_products: 'ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...',
    your_profile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
    your_orders: 'ನಿಮ್ಮ ಆರ್ಡರ್ಗಳು',
    admin_dashboard: 'ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್ಬೋರ್ಡ್',
    admin: 'ನಿರ್ವಾಹಕ',
    hello: 'ನಮಸ್ಕಾರ',
    sign_in: 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    cart: 'ಕಾರ್ಟ್',
    delivering_to: 'ವಿತರಿಸಲಾಗುತ್ತಿದೆ',
    select_location: 'ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    currency: 'ಕರೆನ್ಸಿ',
    language: 'ಭಾಷೆ',
    country: 'ದೇಶ',
    location: 'ಸ್ಥಳ',
    select_currency: 'ಕರೆನ್ಸಿ ಆಯ್ಕೆಮಾಡಿ',
    current: 'ಪ್ರಸ್ತುತ',
    close: 'ಮುಚ್ಚಿ',
    retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    update: 'ನವೀಕರಿಸಿ',
    your_location: 'ನಿಮ್ಮ ಸ್ಥಳ',
    search_location: 'ಸ್ಥಳ ಹುಡುಕಿ...',
    auto_detect: 'ಸ್ವಯಂ ಪತ್ತೆ',
    view_map: 'ನಕ್ಷೆ ನೋಡಿ',
    detecting: 'ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    getting_gps: 'GPS ಪಡೆಯಲಾಗುತ್ತಿದೆ...',
    found: 'ಕಂಡುಬಂದಿದೆ',
    detected: 'ಪತ್ತೆ ಮಾಡಲಾಗಿದೆ',
    selected: 'ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ',
    ip_based: 'IP ಆಧಾರಿತ - ತಪ್ಪಾಗಿರಬಹುದು',
    may_be_inaccurate: 'ತಪ್ಪಾಗಿರಬಹುದು',
    enable_gps_tip: 'ನಿಖರ ಸ್ಥಳಕ್ಕಾಗಿ GPS ಸಕ್ರಿಯಗೊಳಿಸಿ',
    unknown_location: 'ಅಜ್ಞಾತ ಸ್ಥಳ',
    search: 'ಹುಡುಕು',
    all: 'ಎಲ್ಲಾ',
    in_stock: 'ಸ್ಟಾಕ್ನಲ್ಲಿದೆ',
    out_of_stock: 'ಸ್ಟಾಕ್ ಇಲ್ಲ',
    add_to_cart: 'ಕಾರ್ಟ್ಗೆ ಸೇರಿಸಿ',
    buy_now: 'ಈಗ ಖರೀದಿಸಿ',
    description: 'ವಿವರಣೆ',
    reviews: 'ವಿಮರ್ಶೆಗಳು',
    rating: 'ರೇಟಿಂಗ್',
    shipping: 'ಶಿಪ್ಪಿಂಗ್',
    returns: 'ರಿಟರ್ನ್ಸ್',
    payment: 'ಪಾವತಿ',
    order_summary: 'ಆರ್ಡರ್ ಸಾರಾಂಶ',
    subtotal: 'ಉಪಮೊತ್ತ',
    discount: 'ರಿಯಾಯಿತಿ',
    delivery_charge: 'ವಿತರಣಾ ಶುಲ್ಕ',
    proceed_to_checkout: 'ಚೆಕ್ಔಟ್ಗೆ ಮುಂದುವರಿಯಿರಿ',
    continue_shopping: 'ಶಾಪಿಂಗ್ ಮುಂದುವರಿಸಿ',
    place_order: 'ಆರ್ಡರ್ ಇರಿಸಿ',
    order_confirmed: 'ಆರ್ಡರ್ ದೃಢಪಡಿಸಲಾಗಿದೆ',
    order_cancelled: 'ಆರ್ಡರ್ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    track_your_order: 'ನಿಮ್ಮ ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    order_id: 'ಆರ್ಡರ್ ID',
    order_date: 'ಆರ್ಡರ್ ದಿನಾಂಕ',
    order_status: 'ಆರ್ಡರ್ ಸ್ಥಿತಿ',
    delivered: 'ವಿತರಿಸಲಾಗಿದೆ',
    shipped: 'ಶಿಪ್ ಮಾಡಲಾಗಿದೆ',
    processing: 'ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ',
    pending: 'ಬಾಕಿಯಿದೆ',
    cancelled: 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    refunded: 'ಮರುಪಾವತಿ ಮಾಡಲಾಗಿದೆ',
    no_products: 'ಉತ್ಪನ್ನಗಳು ಲಭ್ಯವಿಲ್ಲ',
    shop_description: "ಭಾರತದ ಪ್ರೀಮಿಯಂ ಆನ್ಲೈನ್ ಶಾಪಿಂಗ್ ತಾಣ",
    home_title: 'Sombu ಸ್ಟೋರ್ - ಪ್ರೀಮಿಯಂ ಉತ್ಪನ್ನಗಳು',
    home_description: 'Sombu ಸ್ಟೋರ್ಗೆ ಸುಸ್ವಾಗತ',
    hero_title: 'ನಿಮ್ಮ ಸ್ಟೈಲ್ ಕಂಡುಹಿಡಿಯಿರಿ',
    hero_subtitle: "ನಾವು ಅದ್ಭುತವಾದದ್ದನ್ನು ರಚಿಸುತ್ತಿದ್ದೇವೆ!",
    view_collections: 'ಸಂಗ್ರಹಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    shop_now: 'ಈಗ ಶಾಪಿಂಗ್ ಮಾಡಿ',
    explore_products: 'ಉತ್ಪನ್ನಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    free_shipping: 'ಉಚಿತ ಶಿಪ್ಪಿಂಗ್',
    free_shipping_desc: '₹500 ಮೇಲಿನ ಆರ್ಡರ್ಗಳಿಗೆ',
    secure_payment: 'ಸುರಕ್ಷಿತ ಪಾವತಿ',
    secure_payment_desc: '100% ಸುರಕ್ಷಿತ',
    support: '24/7 ಬೆಂಬಲ',
    support_desc: 'ಸಮರ್ಪಿತ ತಂಡ',
    easy_returns: 'ಸುಲಭ ರಿಟರ್ನ್ಸ್',
    easy_returns_desc: '7 ದಿನಗಳ ರಿಟರ್ನ್',
    happy_customers: 'ಸಂತೋಷದ ಗ್ರಾಹಕರು',
    brands: 'ಬ್ರಾಂಡ್ಗಳು',
    delivery: 'ವಿತರಣೆ*',
    coming_soon: 'ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ',
    soon: 'ಶೀಘ್ರದಲ್ಲೇ',
    curating_collection: "ನಾವು ಅತ್ಯುತ್ತಮ ಸಂಗ್ರಹವನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತಿದ್ದೇವೆ",
    under_construction: 'ಸ್ಟೋರ್ ನಿರ್ಮಾಣದಲ್ಲಿದೆ',
    launching_soon: "ಶೀಘ್ರದಲ್ಲೇ ಪ್ರಾರಂಭಿಸಲಾಗುತ್ತಿದೆ",
    stay_tuned: 'ನಿರೀಕ್ಷಿಸಿರಿ!',
    progress: 'ಪ್ರಗತಿ',
    almost_there: "ಬಹುತೇಕ ಸಿದ್ಧ!",
    'footer_description': 'ನಿಮ್ಮ ಎಲ್ಲಾ ಶಾಪಿಂಗ್ ಅಗತ್ಯಗಳಿಗಾಗಿ ಒಂದೇ ಸ್ಥಳ. ಗುಣಮಟ್ಟದ ಉತ್ಪನ್ನಗಳು, ಅತ್ಯುತ್ತಮ ಬೆಲೆಗಳು, ಮತ್ತು ವೇಗದ ಡೆಲಿವರಿ.',
  'company': 'ಕಂಪನಿ',
  'about_us': 'ನಮ್ಮ ಬಗ್ಗೆ',
  'careers': 'ವೃತ್ತಿ',
  'press': 'ಪ್ರೆಸ್',
  'blog': 'ಬ್ಲಾಗ್',
  'support': 'ಬೆಂಬಲ',
  'help_center': 'ಸಹಾಯ ಕೇಂದ್ರ',
  'contact_us': 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
  'returns': 'ಹಿಂತಿರುಗಿಸುವಿಕೆ',
  'shipping_info': 'ಶಿಪ್ಪಿಂಗ್ ಮಾಹಿತಿ',
  'faqs': 'ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು',
  'track_order': 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
  'legal': 'ಕಾನೂನು',
  'privacy_policy': 'ಗೌಪ್ಯತಾ ನೀತಿ',
  'terms_of_service': 'ಸೇವಾ ನಿಯಮಗಳು',
  'cookie_policy': 'ಕುಕೀ ನೀತಿ',
  'gdpr': 'GDPR',
  'disclaimer': 'ಎಚ್ಚರಿಕೆ',
  'account': 'ಖಾತೆ',
  'my_account': 'ನನ್ನ ಖಾತೆ',
  'orders': 'ಆರ್ಡರ್ಗಳು',
  'wishlist': 'ವಿಶ್ಲಿಸ್ಟ್',
  'cart': 'ಕಾರ್ಟ್',
  'settings': 'ಸೆಟ್ಟಿಂಗ್ಗಳು',
  'all_rights_reserved': 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    current_language: 'ಪ್ರಸ್ತುತ ಭಾಷೆ',
    current_currency: 'ಪ್ರಸ್ತುತ ಕರೆನ್ಸಿ',
    select_language: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    change_language: 'ಭಾಷೆ ಬದಲಾಯಿಸಿ',
    all_languages: 'ಎಲ್ಲಾ ಭಾಷೆಗಳು',
    tamil: 'ತಮಿಳು',
    hindi: 'ಹಿಂದಿ',
    telugu: 'ತೆಲುಗು',
    malayalam: 'ಮಲಯಾಳಂ',
    kannada: 'ಕನ್ನಡ',
    bengali: 'ಬೆಂಗಾಲಿ',
    marathi: 'ಮರಾಠಿ',
    gujarati: 'ಗುಜರಾತಿ',
    punjabi: 'ಪಂಜಾಬಿ',
    english: 'ಇಂಗ್ಲೀಷ್',
  },
  bn: {
    home: 'হোম',
    products: 'পণ্য',
    orders: 'অর্ডার',
    track_order: 'অর্ডার ট্র্যাক করুন',
    login: 'লগইন',
    logout: 'লগআউট',
    wishlist: 'উইশলিস্ট',
    filters: 'ফিল্টার',
    categories: 'বিভাগ',
    all_categories: 'সমস্ত বিভাগ',
    price_range: 'মূল্য পরিসীমা',
    min_price: 'সর্বনিম্ন মূল্য',
    max_price: 'সর্বোচ্চ মূল্য',
    sort_by: 'সাজান',
    newest_first: 'নতুনতম প্রথম',
    price_low_to_high: 'কম থেকে বেশি দাম',
    price_high_to_low: 'বেশি থেকে কম দাম',
    name_a_to_z: 'নাম A থেকে Z',
    apply_filters: 'ফিল্টার প্রয়োগ করুন',
    clear_all: 'সব মুছুন',
    search_products: 'পণ্য খুঁজুন...',
    your_profile: 'আপনার প্রোফাইল',
    your_orders: 'আপনার অর্ডার',
    admin_dashboard: 'অ্যাডমিন ড্যাশবোর্ড',
    admin: 'প্রশাসক',
    hello: 'হ্যালো',
    sign_in: 'সাইন ইন করুন',
    cart: 'কার্ট',
    delivering_to: 'ডেলিভারি হচ্ছে',
    select_location: 'অবস্থান নির্বাচন করুন',
    currency: 'মুদ্রা',
    language: 'ভাষা',
    country: 'দেশ',
    location: 'অবস্থান',
    select_currency: 'মুদ্রা নির্বাচন করুন',
    current: 'বর্তমান',
    close: 'বন্ধ করুন',
    retry: 'আবার চেষ্টা করুন',
    update: 'আপডেট করুন',
    your_location: 'আপনার অবস্থান',
    search_location: 'অবস্থান খুঁজুন...',
    auto_detect: 'স্বয়ংক্রিয় সনাক্তকরণ',
    view_map: 'ম্যাপ দেখুন',
    detecting: 'সনাক্ত করা হচ্ছে...',
    getting_gps: 'GPS পাচ্ছি...',
    found: 'পাওয়া গেছে',
    detected: 'সনাক্ত করা হয়েছে',
    selected: 'নির্বাচিত',
    ip_based: 'IP ভিত্তিক - ভুল হতে পারে',
    may_be_inaccurate: 'ভুল হতে পারে',
    enable_gps_tip: 'সঠিক অবস্থানের জন্য GPS সক্রিয় করুন',
    unknown_location: 'অজানা অবস্থান',
    search: 'খুঁজুন',
    all: 'সব',
    in_stock: 'স্টকে আছে',
    out_of_stock: 'স্টক শেষ',
    add_to_cart: 'কার্টে যোগ করুন',
    buy_now: 'এখনই কিনুন',
    description: 'বর্ণনা',
    reviews: 'রিভিউ',
    rating: 'রেটিং',
    shipping: 'শিপিং',
    returns: 'রিটার্ন',
    payment: 'পেমেন্ট',
    order_summary: 'অর্ডার সারসংক্ষেপ',
    subtotal: 'সাবটোটাল',
    discount: 'ছাড়',
    delivery_charge: 'ডেলিভারি চার্জ',
    proceed_to_checkout: 'চেকআউটে যান',
    continue_shopping: 'শপিং চালিয়ে যান',
    place_order: 'অর্ডার করুন',
    order_confirmed: 'অর্ডার নিশ্চিত করা হয়েছে',
    order_cancelled: 'অর্ডার বাতিল করা হয়েছে',
    track_your_order: 'আপনার অর্ডার ট্র্যাক করুন',
    order_id: 'অর্ডার আইডি',
    order_date: 'অর্ডার তারিখ',
    order_status: 'অর্ডার অবস্থা',
    delivered: 'ডেলিভারি করা হয়েছে',
    shipped: 'শিপ করা হয়েছে',
    processing: 'প্রক্রিয়াকরণ',
    pending: 'মুলতুবি',
    cancelled: 'বাতিল',
    refunded: 'রিফান্ড করা হয়েছে',
    no_products: 'কোন পণ্য পাওয়া যায়নি',
    shop_description: "ভারতের প্রিমিয়াম অনলাইন শপিং গন্তব্য",
    home_title: 'Sombu স্টোর - প্রিমিয়াম পণ্য',
    home_description: 'Sombu স্টোরে স্বাগতম',
    hero_title: 'আপনার স্টাইল আবিষ্কার করুন',
    hero_subtitle: "আমরা অসাধারণ কিছু তৈরি করছি!",
    view_collections: 'সংগ্রহ দেখুন',
    shop_now: 'এখনই কেনাকাটা করুন',
    explore_products: 'পণ্য অন্বেষণ করুন',
    free_shipping: 'বিনামূল্যে শিপিং',
    free_shipping_desc: '₹500 এর বেশি অর্ডারে',
    secure_payment: 'নিরাপদ পেমেন্ট',
    secure_payment_desc: '100% নিরাপদ',
    support: '24/7 সাপোর্ট',
    support_desc: 'নিবেদিত দল',
    easy_returns: 'সহজ রিটার্ন',
    easy_returns_desc: '৭ দিন রিটার্ন',
    happy_customers: 'সন্তুষ্ট গ্রাহক',
    brands: 'ব্র্যান্ড',
    delivery: 'ডেলিভারি*',
    coming_soon: 'শীঘ্রই আসছে',
    soon: 'শীঘ্রই',
    curating_collection: "আমরা সেরা সংগ্রহ প্রস্তুত করছি",
    under_construction: 'স্টোর নির্মাণাধীন',
    launching_soon: "শীঘ্রই চালু হচ্ছে",
    stay_tuned: 'আমাদের সাথে থাকুন!',
    progress: 'অগ্রগতি',
    almost_there: "প্রায় শেষ!",
    'footer_description': 'আপনার সমস্ত শপিং প্রয়োজনের জন্য এক-স্টপ গন্তব্য। গুণমানের পণ্য, সেরা দাম, এবং দ্রুত ডেলিভারি।',
  'company': 'কোম্পানি',
  'about_us': 'আমাদের সম্পর্কে',
  'careers': 'কর্মজীবন',
  'press': 'প্রেস',
  'blog': 'ব্লগ',
  'support': 'সহায়তা',
  'help_center': 'সহায়তা কেন্দ্র',
  'contact_us': 'আমাদের সাথে যোগাযোগ করুন',
  'returns': 'রিটার্ন',
  'shipping_info': 'শিপিং তথ্য',
  'faqs': 'সাধারণ জিজ্ঞাসা',
  'track_order': 'অর্ডার ট্র্যাক করুন',
  'legal': 'আইনি',
  'privacy_policy': 'গোপনীয়তা নীতি',
  'terms_of_service': 'সেবার শর্তাবলী',
  'cookie_policy': 'কুকি নীতি',
  'gdpr': 'জিডিপিআর',
  'disclaimer': 'দাবি পরিত্যাগ',
  'account': 'অ্যাকাউন্ট',
  'my_account': 'আমার অ্যাকাউন্ট',
  'orders': 'অর্ডার',
  'wishlist': 'উইশলিস্ট',
  'cart': 'কার্ট',
  'settings': 'সেটিংস',
  'all_rights_reserved': 'সব অধিকার সংরক্ষিত।',
    current_language: 'বর্তমান ভাষা',
    current_currency: 'বর্তমান মুদ্রা',
    select_language: 'ভাষা নির্বাচন করুন',
    change_language: 'ভাষা পরিবর্তন করুন',
    all_languages: 'সব ভাষা',
    tamil: 'তামিল',
    hindi: 'হিন্দি',
    telugu: 'তেলেগু',
    malayalam: 'মালায়ালাম',
    kannada: 'কন্নড়',
    bengali: 'বাংলা',
    marathi: 'মারাঠি',
    gujarati: 'গুজরাটি',
    punjabi: 'পাঞ্জাবি',
    english: 'ইংরেজি',
  },
  mr: {
    home: 'मुख्यपृष्ठ',
    products: 'उत्पादने',
    orders: 'ऑर्डर',
    track_order: 'ऑर्डर ट्रॅक करा',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    wishlist: 'विशलिस्ट',
    filters: 'फिल्टर',
    categories: 'श्रेणी',
    all_categories: 'सर्व श्रेणी',
    price_range: 'किंमत श्रेणी',
    min_price: 'किमान किंमत',
    max_price: 'कमाल किंमत',
    sort_by: 'क्रमवारी',
    newest_first: 'नवीन प्रथम',
    price_low_to_high: 'कमी ते जास्त किंमत',
    price_high_to_low: 'जास्त ते कमी किंमत',
    name_a_to_z: 'नाव A ते Z',
    apply_filters: 'फिल्टर लागू करा',
    clear_all: 'सर्व हटवा',
    search_products: 'उत्पादने शोधा...',
    your_profile: 'तुमचे प्रोफाइल',
    your_orders: 'तुमचे ऑर्डर',
    admin_dashboard: 'प्रशासक डॅशबोर्ड',
    admin: 'प्रशासक',
    hello: 'नमस्कार',
    sign_in: 'साइन इन करा',
    cart: 'कार्ट',
    delivering_to: 'वितरित केले जात आहे',
    select_location: 'स्थान निवडा',
    currency: 'चलन',
    language: 'भाषा',
    country: 'देश',
    location: 'स्थान',
    select_currency: 'चलन निवडा',
    current: 'सद्य',
    close: 'बंद करा',
    retry: 'पुन्हा प्रयत्न करा',
    update: 'अद्यतनित करा',
    your_location: 'तुमचे स्थान',
    search_location: 'स्थान शोधा...',
    auto_detect: 'स्वयं शोधा',
    view_map: 'नकाशा पहा',
    detecting: 'शोधत आहे...',
    getting_gps: 'GPS मिळवत आहे...',
    found: 'सापडले',
    detected: 'आढळले',
    selected: 'निवडले',
    ip_based: 'IP आधारित - चुकीचे असू शकते',
    may_be_inaccurate: 'चुकीचे असू शकते',
    enable_gps_tip: 'अचूक स्थानासाठी GPS सक्षम करा',
    unknown_location: 'अज्ञात स्थान',
    search: 'शोधा',
    all: 'सर्व',
    in_stock: 'स्टॉकमध्ये',
    out_of_stock: 'स्टॉक संपला',
    add_to_cart: 'कार्टमध्ये घाला',
    buy_now: 'आत्ता विकत घ्या',
    description: 'वर्णन',
    reviews: 'पुनरावलोकने',
    rating: 'रेटिंग',
    shipping: 'शिपिंग',
    returns: 'रिटर्न',
    payment: 'पेमेंट',
    order_summary: 'ऑर्डर सारांश',
    subtotal: 'उपएकूण',
    discount: 'सूट',
    delivery_charge: 'वितरण शुल्क',
    proceed_to_checkout: 'चेकआउटवर जा',
    continue_shopping: 'खरेदी सुरू ठेवा',
    place_order: 'ऑर्डर द्या',
    order_confirmed: 'ऑर्डर पुष्टी झाली',
    order_cancelled: 'ऑर्डर रद्द',
    track_your_order: 'तुमचा ऑर्डर ट्रॅक करा',
    order_id: 'ऑर्डर आयडी',
    order_date: 'ऑर्डर तारीख',
    order_status: 'ऑर्डर स्थिती',
    delivered: 'वितरित',
    shipped: 'शिप केले',
    processing: 'प्रक्रिया',
    pending: 'प्रलंबित',
    cancelled: 'रद्द',
    refunded: 'परत केले',
    no_products: 'उत्पादने उपलब्ध नाहीत',
    shop_description: "भारताचे प्रीमियम ऑनलाइन शॉपिंग गंतव्य",
    home_title: 'Sombu स्टोअर - प्रीमियम उत्पादने',
    home_description: 'Sombu स्टोअरमध्ये आपले स्वागत आहे',
    hero_title: 'तुमची स्टाईल शोधा',
    hero_subtitle: "आम्ही काहीतरी अद्भुत तयार करत आहोत!",
    view_collections: 'संग्रह पहा',
    shop_now: 'आत्ता खरेदी करा',
    explore_products: 'उत्पादने एक्सप्लोर करा',
    free_shipping: 'मोफत शिपिंग',
    free_shipping_desc: '₹500 पेक्षा जास्त ऑर्डरवर',
    secure_payment: 'सुरक्षित पेमेंट',
    secure_payment_desc: '100% सुरक्षित',
    support: '24/7 सपोर्ट',
    support_desc: 'समर्पित टीम',
    easy_returns: 'सोपे रिटर्न',
    easy_returns_desc: '7 दिवस रिटर्न',
    happy_customers: 'आनंदी ग्राहक',
    brands: 'ब्रँड',
    delivery: 'वितरण*',
    coming_soon: 'लवकरच येत आहे',
    soon: 'लवकरच',
    curating_collection: "आम्ही सर्वोत्तम संग्रह तयार करत आहोत",
    under_construction: 'स्टोअर बांधकामाधीन',
    launching_soon: "लवकरच लाँच होत आहे",
    stay_tuned: 'तयार रहा!',
    progress: 'प्रगती',
    almost_there: "जवळपास पूर्ण!",
    current_language: 'सद्य भाषा',
    current_currency: 'सद्य चलन',
    select_language: 'भाषा निवडा',
    change_language: 'भाषा बदला',
    all_languages: 'सर्व भाषा',
     'footer_description': 'तुमच्या सर्व खरेदी गरजांसाठी वन-स्टॉप गंतव्य. दर्जेदार उत्पादने, सर्वोत्तम किंमती, आणि जलद वितरण.',
  'company': 'कंपनी',
  'about_us': 'आमच्याबद्दल',
  'careers': 'करियर',
  'press': 'प्रेस',
  'blog': 'ब्लॉग',
  'support': 'सहाय्य',
  'help_center': 'सहाय्य केंद्र',
  'contact_us': 'आमच्याशी संपर्क साधा',
  'returns': 'परतावा',
  'shipping_info': 'शिपिंग माहिती',
  'faqs': 'सामान्य प्रश्न',
  'track_order': 'ऑर्डर ट्रॅक करा',
  'legal': 'कायदेशीर',
  'privacy_policy': 'गोपनीयता धोरण',
  'terms_of_service': 'सेवा अटी',
  'cookie_policy': 'कुकी धोरण',
  'gdpr': 'जीडीपीआर',
  'disclaimer': 'अस्वीकरण',
  'account': 'खाते',
  'my_account': 'माझे खाते',
  'orders': 'ऑर्डर',
  'wishlist': 'विशलिस्ट',
  'cart': 'कार्ट',
  'settings': 'सेटिंग्ज',
  'all_rights_reserved': 'सर्व हक्क राखीव.',
    tamil: 'तमिळ',
    hindi: 'हिंदी',
    telugu: 'तेलुगू',
    malayalam: 'मल्याळम',
    kannada: 'कन्नड',
    bengali: 'बंगाली',
    marathi: 'मराठी',
    gujarati: 'गुजराती',
    punjabi: 'पंजाबी',
    english: 'इंग्रजी',
  },
  gu: {
    home: 'હોમ',
    products: 'ઉત્પાદનો',
    orders: 'ઓર્ડર',
    track_order: 'ઓર્ડર ટ્રેક કરો',
    login: 'લૉગિન',
    logout: 'લૉગઆઉટ',
    wishlist: 'વિશલિસ્ટ',
    filters: 'ફિલ્ટર્સ',
    categories: 'શ્રેણીઓ',
    all_categories: 'બધી શ્રેણીઓ',
    price_range: 'કિંમત શ્રેણી',
    min_price: 'લઘુત્તમ કિંમત',
    max_price: 'મહત્તમ કિંમત',
    sort_by: 'ક્રમમાં ગોઠવો',
    newest_first: 'નવું પ્રથમ',
    price_low_to_high: 'ઓછી થી વધુ કિંમત',
    price_high_to_low: 'વધુ થી ઓછી કિંમત',
    name_a_to_z: 'નામ A થી Z',
    apply_filters: 'ફિલ્ટર્સ લાગુ કરો',
    clear_all: 'બધું સાફ કરો',
    search_products: 'ઉત્પાદનો શોધો...',
    your_profile: 'તમારું પ્રોફાઇલ',
    your_orders: 'તમારા ઓર્ડર',
    admin_dashboard: 'એડમિન ડેશબોર્ડ',
    admin: 'વ્યવસ્થાપક',
    hello: 'નમસ્તે',
    sign_in: 'સાઇન ઇન કરો',
    cart: 'કાર્ટ',
    delivering_to: 'ડિલિવરી થઈ રહી છે',
    select_location: 'સ્થાન પસંદ કરો',
    currency: 'ચલણ',
    language: 'ભાષા',
    country: 'દેશ',
    location: 'સ્થાન',
    select_currency: 'ચલણ પસંદ કરો',
    current: 'વર્તમાન',
    close: 'બંધ કરો',
    retry: 'ફરી પ્રયાસ કરો',
    update: 'અપડેટ કરો',
    your_location: 'તમારું સ્થાન',
    search_location: 'સ્થાન શોધો...',
    auto_detect: 'આપોઆપ શોધો',
    view_map: 'નકશો જુઓ',
    detecting: 'શોધી રહ્યા છે...',
    getting_gps: 'GPS મેળવી રહ્યા છે...',
    found: 'મળી આવ્યું',
    detected: 'શોધાયું',
    selected: 'પસંદ કરેલ',
    ip_based: 'IP આધારિત - ખોટું હોઈ શકે',
    may_be_inaccurate: 'ખોટું હોઈ શકે',
    enable_gps_tip: 'ચોક્કસ સ્થાન માટે GPS સક્ષમ કરો',
    unknown_location: 'અજ્ઞાત સ્થાન',
    search: 'શોધો',
    all: 'બધા',
    in_stock: 'સ્ટોકમાં',
    out_of_stock: 'સ્ટોક સમાપ્ત',
    add_to_cart: 'કાર્ટમાં ઉમેરો',
    buy_now: 'હવે ખરીદો',
    description: 'વર્ણન',
    reviews: 'સમીક્ષાઓ',
    rating: 'રેટિંગ',
    shipping: 'શિપિંગ',
    returns: 'રિટર્ન્સ',
    payment: 'ચુકવણી',
    order_summary: 'ઓર્ડર સારાંશ',
    subtotal: 'પેટા સરવાળો',
    discount: 'ડિસ્કાઉન્ટ',
    delivery_charge: 'ડિલિવરી ચાર્જ',
    proceed_to_checkout: 'ચેકઆઉટ પર જાઓ',
    continue_shopping: 'શોપિંગ ચાલુ રાખો',
    place_order: 'ઓર્ડર મૂકો',
    order_confirmed: 'ઓર્ડર કન્ફર્મ થયો',
    order_cancelled: 'ઓર્ડર રદ થયો',
    track_your_order: 'તમારો ઓર્ડર ટ્રેક કરો',
    order_id: 'ઓર્ડર ID',
    order_date: 'ઓર્ડર તારીખ',
    order_status: 'ઓર્ડર સ્થિતિ',
    delivered: 'ડિલિવર થયું',
    shipped: 'શિપ થયું',
    processing: 'પ્રોસેસ થઈ રહ્યું છે',
    pending: 'બાકી',
    cancelled: 'રદ થયું',
    refunded: 'રિફંડ થયું',
    no_products: 'કોઈ ઉત્પાદનો ઉપલબ્ધ નથી',
    shop_description: "ભારતનું પ્રીમિયમ ઓનલાઇન શોપિંગ સ્થળ",
    home_title: 'Sombu સ્ટોર - પ્રીમિયમ ઉત્પાદનો',
    home_description: 'Sombu સ્ટોરમાં આપનું સ્વાગત છે',
    hero_title: 'તમારી સ્ટાઇલ શોધો',
    hero_subtitle: "અમે કંઈક અદ્ભુત બનાવી રહ્યા છીએ!",
    view_collections: 'કલેક્શન્સ જુઓ',
    shop_now: 'હવે ખરીદી કરો',
    explore_products: 'ઉત્પાદનો અન્વેષણ કરો',
    free_shipping: 'મફત શિપિંગ',
    free_shipping_desc: '₹500 થી વધુ ઓર્ડર પર',
    secure_payment: 'સુરક્ષિત ચુકવણી',
    secure_payment_desc: '100% સુરક્ષિત',
    support: '24/7 સપોર્ટ',
    support_desc: 'સમર્પિત ટીમ',
    easy_returns: 'સરળ રિટર્ન્સ',
    easy_returns_desc: '7 દિવસ રિટર્ન',
    happy_customers: 'ખુશ ગ્રાહકો',
    brands: 'બ્રાન્ડ્સ',
    delivery: 'ડિલિવરી*',
    coming_soon: 'ટૂંક સમયમાં આવી રહ્યું છે',
    soon: 'ટૂંક સમયમાં',
    curating_collection: "અમે શ્રેષ્ઠ કલેક્શન તૈયાર કરી રહ્યા છીએ",
    under_construction: 'સ્ટોર બાંધકામ હેઠળ',
    launching_soon: "ટૂંક સમયમાં લોન્ચ થઈ રહ્યું છે",
    stay_tuned: 'જોડાયેલા રહો!',
    progress: 'પ્રગતિ',
    almost_there: "લગભગ ત્યાં!",
    'footer_description': 'તમારી તમામ શોપિંગ જરૂરિયાતો માટે વન-સ્ટોપ ગંતવ્ય. ગુણવત્તાયુક્ત ઉત્પાદનો, શ્રેષ્ઠ ભાવો, અને ઝડપી ડિલિવરી.',
  'company': 'કંપની',
  'about_us': 'અમારા વિશે',
  'careers': 'કારકિર્દી',
  'press': 'પ્રેસ',
  'blog': 'બ્લોગ',
  'support': 'સપોર્ટ',
  'help_center': 'સહાય કેન્દ્ર',
  'contact_us': 'અમારો સંપર્ક કરો',
  'returns': 'રિટર્ન્સ',
  'shipping_info': 'શિપિંગ માહિતી',
  'faqs': 'વારંવાર પૂછાતા પ્રશ્નો',
  'track_order': 'ઓર્ડર ટ્રેક કરો',
  'legal': 'કાનૂની',
  'privacy_policy': 'ગોપનીયતા નીતિ',
  'terms_of_service': 'સેવાની શરતો',
  'cookie_policy': 'કૂકી નીતિ',
  'gdpr': 'જીડીપીઆર',
  'disclaimer': 'અસ્વીકરણ',
  'account': 'ખાતું',
  'my_account': 'મારું ખાતું',
  'orders': 'ઓર્ડર',
  'wishlist': 'વિશલિસ્ટ',
  'cart': 'કાર્ટ',
  'settings': 'સેટિંગ્સ',
  'all_rights_reserved': 'બધા હક્કો સુરક્ષિત.',
    current_language: 'વર્તમાન ભાષા',
    current_currency: 'વર્તમાન ચલણ',
    select_language: 'ભાષા પસંદ કરો',
    change_language: 'ભાષા બદલો',
    all_languages: 'બધી ભાષાઓ',
    tamil: 'તમિલ',
    hindi: 'હિન્દી',
    telugu: 'તેલુગુ',
    malayalam: 'મલયાલમ',
    kannada: 'કન્નડ',
    bengali: 'બંગાળી',
    marathi: 'મરાઠી',
    gujarati: 'ગુજરાતી',
    punjabi: 'પંજાબી',
    english: 'અંગ્રેજી',
  },
  pa: {
    home: 'ਘਰ',
    products: 'ਉਤਪਾਦ',
    orders: 'ਆਰਡਰ',
    track_order: 'ਆਰਡਰ ਟਰੈਕ ਕਰੋ',
    login: 'ਲੌਗਿਨ',
    logout: 'ਲੌਗਆਉਟ',
    wishlist: 'ਵਿਸ਼ਲਿਸਟ',
    filters: 'ਫਿਲਟਰ',
    categories: 'ਸ਼੍ਰੇਣੀਆਂ',
    all_categories: 'ਸਾਰੀਆਂ ਸ਼੍ਰੇਣੀਆਂ',
    price_range: 'ਕੀਮਤ ਸੀਮਾ',
    min_price: 'ਘੱਟੋ-ਘੱਟ ਕੀਮਤ',
    max_price: 'ਵੱਧ ਤੋਂ ਵੱਧ ਕੀਮਤ',
    sort_by: 'ਕ੍ਰਮਬੱਧ ਕਰੋ',
    newest_first: 'ਨਵਾਂ ਪਹਿਲਾਂ',
    price_low_to_high: 'ਘੱਟ ਤੋਂ ਵੱਧ ਕੀਮਤ',
    price_high_to_low: 'ਵੱਧ ਤੋਂ ਘੱਟ ਕੀਮਤ',
    name_a_to_z: 'ਨਾਮ A ਤੋਂ Z',
    apply_filters: 'ਫਿਲਟਰ ਲਾਗੂ ਕਰੋ',
    clear_all: 'ਸਭ ਸਾਫ਼ ਕਰੋ',
    search_products: 'ਉਤਪਾਦ ਲੱਭੋ...',
    your_profile: 'ਤੁਹਾਡਾ ਪ੍ਰੋਫਾਈਲ',
    your_orders: 'ਤੁਹਾਡੇ ਆਰਡਰ',
    admin_dashboard: 'ਐਡਮਿਨ ਡੈਸ਼ਬੋਰਡ',
    admin: 'ਪ੍ਰਬੰਧਕ',
    hello: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
    sign_in: 'ਸਾਈਨ ਇਨ ਕਰੋ',
    cart: 'ਕਾਰਟ',
    delivering_to: 'ਡਿਲੀਵਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ',
    select_location: 'ਸਥਾਨ ਚੁਣੋ',
    currency: 'ਮੁਦਰਾ',
    language: 'ਭਾਸ਼ਾ',
    country: 'ਦੇਸ਼',
    location: 'ਸਥਾਨ',
    select_currency: 'ਮੁਦਰਾ ਚੁਣੋ',
    current: 'ਮੌਜੂਦਾ',
    close: 'ਬੰਦ ਕਰੋ',
    retry: 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    update: 'ਅਪਡੇਟ ਕਰੋ',
    your_location: 'ਤੁਹਾਡਾ ਸਥਾਨ',
    search_location: 'ਸਥਾਨ ਲੱਭੋ...',
    auto_detect: 'ਆਟੋ-ਖੋਜ',
    view_map: 'ਨਕਸ਼ਾ ਵੇਖੋ',
    detecting: 'ਖੋਜ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
    getting_gps: 'GPS ਪ੍ਰਾਪਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    found: 'ਮਿਲਿਆ',
    detected: 'ਖੋਜਿਆ ਗਿਆ',
    selected: 'ਚੁਣਿਆ ਗਿਆ',
    ip_based: 'IP ਅਧਾਰਿਤ - ਗਲਤ ਹੋ ਸਕਦਾ ਹੈ',
    may_be_inaccurate: 'ਗਲਤ ਹੋ ਸਕਦਾ ਹੈ',
    enable_gps_tip: 'ਸਹੀ ਸਥਾਨ ਲਈ GPS ਚਾਲੂ ਕਰੋ',
    unknown_location: 'ਅਣਜਾਣ ਸਥਾਨ',
    search: 'ਖੋਜੋ',
    all: 'ਸਭ',
    in_stock: 'ਸਟੋਕ ਵਿੱਚ',
    out_of_stock: 'ਸਟੋਕ ਖਤਮ',
    add_to_cart: 'ਕਾਰਟ ਵਿੱਚ ਪਾਓ',
    buy_now: 'ਹੁਣੇ ਖਰੀਦੋ',
    description: 'ਵੇਰਵਾ',
    reviews: 'ਸਮੀਖਿਆਵਾਂ',
    rating: 'ਰੇਟਿੰਗ',
    shipping: 'ਸ਼ਿਪਿੰਗ',
    returns: 'ਰਿਟਰਨ',
    payment: 'ਭੁਗਤਾਨ',
    order_summary: 'ਆਰਡਰ ਸਾਰਾਂਸ਼',
    subtotal: 'ਉਪ-ਯੋਗ',
    discount: 'ਛੂਟ',
    delivery_charge: 'ਡਿਲੀਵਰੀ ਚਾਰਜ',
    proceed_to_checkout: 'ਚੈਕਆਉਟ ਵੱਲ ਵਧੋ',
    continue_shopping: 'ਖਰੀਦਦਾਰੀ ਜਾਰੀ ਰੱਖੋ',
    place_order: 'ਆਰਡਰ ਦਿਓ',
    order_confirmed: 'ਆਰਡਰ ਪੁਸ਼ਟੀ ਹੋਈ',
    order_cancelled: 'ਆਰਡਰ ਰੱਦ',
    track_your_order: 'ਆਪਣਾ ਆਰਡਰ ਟਰੈਕ ਕਰੋ',
    order_id: 'ਆਰਡਰ ID',
    order_date: 'ਆਰਡਰ ਮਿਤੀ',
    order_status: 'ਆਰਡਰ ਸਥਿਤੀ',
    delivered: 'ਡਿਲੀਵਰ ਕੀਤਾ',
    shipped: 'ਸ਼ਿਪ ਕੀਤਾ',
    processing: 'ਪ੍ਰੋਸੈਸਿੰਗ',
    pending: 'ਬਾਕੀ',
    cancelled: 'ਰੱਦ',
    refunded: 'ਰਿਫੰਡ ਕੀਤਾ',
    no_products: 'ਕੋਈ ਉਤਪਾਦ ਉਪਲਬਧ ਨਹੀਂ',
    shop_description: "ਭਾਰਤ ਦਾ ਪ੍ਰੀਮੀਅਮ ਔਨਲਾਈਨ ਖਰੀਦਾਰੀ ਸਥਾਨ",
    home_title: 'Sombu ਸਟੋਰ - ਪ੍ਰੀਮੀਅਮ ਉਤਪਾਦ',
    home_description: 'Sombu ਸਟੋਰ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    hero_title: 'ਆਪਣੀ ਸਟਾਈਲ ਲੱਭੋ',
    hero_subtitle: "ਅਸੀਂ ਕੁਝ ਅਦਭੁਤ ਬਣਾ ਰਹੇ ਹਾਂ!",
    view_collections: 'ਕਲੈਕਸ਼ਨ ਦੇਖੋ',
    shop_now: 'ਹੁਣੇ ਖਰੀਦੋ',
    explore_products: 'ਉਤਪਾਦ ਖੋਜੋ',
    free_shipping: 'ਮੁਫਤ ਸ਼ਿਪਿੰਗ',
    free_shipping_desc: '₹500 ਤੋਂ ਵੱਧ ਆਰਡਰਾਂ ਲਈ',
    secure_payment: 'ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ',
    secure_payment_desc: '100% ਸੁਰੱਖਿਅਤ',
    support: '24/7 ਸਹਾਇਤਾ',
    support_desc: 'ਸਮਰਪਿਤ ਟੀਮ',
    easy_returns: 'ਆਸਾਨ ਰਿਟਰਨ',
    easy_returns_desc: '7 ਦਿਨ ਰਿਟਰਨ',
    happy_customers: 'ਖੁਸ਼ ਗਾਹਕ',
    brands: 'ਬ੍ਰਾਂਡ',
    delivery: 'ਡਿਲੀਵਰੀ*',
    coming_soon: 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ',
    soon: 'ਜਲਦੀ',
    curating_collection: "ਅਸੀਂ ਵਧੀਆ ਕਲੈਕਸ਼ਨ ਤਿਆਰ ਕਰ ਰਹੇ ਹਾਂ",
    under_construction: 'ਸਟੋਰ ਉਸਾਰੀ ਅਧੀਨ',
    launching_soon: "ਜਲਦੀ ਲਾਂਚ ਹੋ ਰਿਹਾ ਹੈ",
    stay_tuned: 'ਜੁੜੇ ਰਹੋ!',
    progress: 'ਤਰੱਕੀ',
    almost_there: "ਲਗਭਗ ਤਿਆਰ!",
    'footer_description': 'ਤੁਹਾਡੀਆਂ ਸਾਰੀਆਂ ਖਰੀਦਦਾਰੀ ਲੋੜਾਂ ਲਈ ਇੱਕ-ਸਟਾਪ ਮੰਜ਼ਿਲ। ਗੁਣਵੱਤਾ ਵਾਲੇ ਉਤਪਾਦ, ਵਧੀਆ ਕੀਮਤਾਂ, ਅਤੇ ਤੇਜ਼ ਡਿਲੀਵਰੀ।',
  'company': 'ਕੰਪਨੀ',
  'about_us': 'ਸਾਡੇ ਬਾਰੇ',
  'careers': 'ਕੈਰੀਅਰ',
  'press': 'ਪ੍ਰੈਸ',
  'blog': 'ਬਲੌਗ',
  'support': 'ਸਹਾਇਤਾ',
  'help_center': 'ਸਹਾਇਤਾ ਕੇਂਦਰ',
  'contact_us': 'ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
  'returns': 'ਵਾਪਸੀ',
  'shipping_info': 'ਸ਼ਿਪਿੰਗ ਜਾਣਕਾਰੀ',
  'faqs': 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ',
  'track_order': 'ਆਰਡਰ ਟਰੈਕ ਕਰੋ',
  'legal': 'ਕਾਨੂੰਨੀ',
  'privacy_policy': 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
  'terms_of_service': 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
  'cookie_policy': 'ਕੁੱਕੀ ਨੀਤੀ',
  'gdpr': 'ਜੀਡੀਪੀਆਰ',
  'disclaimer': 'ਅਸਵੀਕਾਰ',
  'account': 'ਖਾਤਾ',
  'my_account': 'ਮੇਰਾ ਖਾਤਾ',
  'orders': 'ਆਰਡਰ',
  'wishlist': 'ਵਿਸ਼ਲਿਸਟ',
  'cart': 'ਕਾਰਟ',
  'settings': 'ਸੈਟਿੰਗਜ਼',
  'all_rights_reserved': 'ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।',
    current_language: 'ਮੌਜੂਦਾ ਭਾਸ਼ਾ',
    current_currency: 'ਮੌਜੂਦਾ ਮੁਦਰਾ',
    select_language: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    change_language: 'ਭਾਸ਼ਾ ਬਦਲੋ',
    all_languages: 'ਸਾਰੀਆਂ ਭਾਸ਼ਾਵਾਂ',
    tamil: 'ਤਮਿਲ',
    hindi: 'ਹਿੰਦੀ',
    telugu: 'ਤੇਲਗੂ',
    malayalam: 'ਮਲਿਆਲਮ',
    kannada: 'ਕੰਨੜ',
    bengali: 'ਬੰਗਾਲੀ',
    marathi: 'ਮਰਾਠੀ',
    gujarati: 'ਗੁਜਰਾਤੀ',
    punjabi: 'ਪੰਜਾਬੀ',
    english: 'ਅੰਗਰੇਜ਼ੀ',
  },
};

// ✅ AppProvider Component
export const AppProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [currency, setCurrency] = useState({ code: 'INR', symbol: '₹' });
  const [country, setCountry] = useState({ code: 'IN', name: 'India', flag: '🇮🇳' });
  const [isLoaded, setIsLoaded] = useState(false);

  // ✅ Load saved preferences from localStorage
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('preferredLanguage');
      const savedCurrency = localStorage.getItem('preferredCurrency');
      
      if (savedLanguage && languages.find(l => l.code === savedLanguage)) {
        setLanguage(savedLanguage);
      }
      
      if (savedCurrency) {
        try {
          setCurrency(JSON.parse(savedCurrency));
        } catch (e) {
          setCurrency({ code: 'INR', symbol: '₹' });
        }
      }
    }
    setIsLoaded(true);
  }, []);

  // ✅ Change language - Simple and clean
  const changeLanguage = useCallback((langCode) => {
    setLanguage(langCode);
    localStorage.setItem('preferredLanguage', langCode);
    const lang = languages.find(l => l.code === langCode);
    toast.success(`🌐 ${lang?.name || langCode} selected`);
  }, []);

  // ✅ Change currency
  const changeCurrency = useCallback((currencyData) => {
    setCurrency(currencyData);
    localStorage.setItem('preferredCurrency', JSON.stringify(currencyData));
    toast.success(`💱 ${currencyData.symbol} ${currencyData.code} selected`);
  }, []);

  // ✅ Translation function
  const t = useCallback((key) => {
    const translation = translations[language]?.[key];
    if (translation) return translation;
    return translations.en?.[key] || key;
  }, [language]);

  // ✅ Format price
  const formatPrice = useCallback((amount) => {
    const symbol = currency.symbol || '₹';
    return `${symbol} ${Number(amount).toFixed(2)}`;
  }, [currency]);

  // ✅ Memoized values
  const currentLanguage = useMemo(() => 
    languages.find(l => l.code === language) || languages[0],
    [language]
  );

  const value = useMemo(() => ({
    language,
    currency,
    country,
    currentLanguage,
    currentCurrency: currency,
    changeLanguage,
    changeCurrency,
    setLanguage,
    setCurrency,
    setCountry,
    t,
    formatPrice,
    languages,
    currencies,
    isLoaded,
  }), [
    language,
    currency,
    country,
    currentLanguage,
    changeLanguage,
    changeCurrency,
    setLanguage,
    setCurrency,
    setCountry,
    t,
    formatPrice,
    isLoaded,
  ]);

  return (
    <AppContext.Provider value={value}>
      {children}
    </AppContext.Provider>
  );
};

// ✅ Export useApp hook
export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
};

export default AppProvider;