// // src/context/AppContext.jsx
// 'use client';

// import React, { createContext, useState, useEffect } from 'react';

// // ✅ Create Context
// export const AppContext = createContext();

// // ✅ Translations
// const translations = {
//   en: {
//     // Navigation
//     home: 'Home',
//     products: 'Products',
//     orders: 'Orders',
//     track: 'Track Order',
//     login: 'Login',
//     logout: 'Logout',
//     wishlist: 'Wishlist',
//     filters: 'Filters',
//     categories: 'Categories',
//     all_categories: 'All Categories',
//     price_range: 'Price Range',
//     min_price: 'Min Price',
//     max_price: 'Max Price',
//     sort_by: 'Sort By',
//     newest_first: 'Newest First',
//     price_low_to_high: 'Price: Low to High',
//     price_high_to_low: 'Price: High to Low',
//     name_a_to_z: 'Name: A to Z',
//     apply_filters: 'Apply Filters',
//     clear_all: 'Clear All Filters',
//     search_products: 'Search for products, brands, and categories...',
//     your_profile: 'Your Profile',
//     your_orders: 'Your Orders',
//     track_order: 'Track Order',
//     admin_dashboard: 'Admin Dashboard',
//     select_language: 'Select Language',
//     shop_now: 'Shop Now',
//     featured: 'Featured',
//     trending: 'Trending',
//     new_arrivals: 'New Arrivals',
//     best_sellers: 'Best Sellers',
//     added_to_cart: 'Added to cart',
//     removed_from_cart: 'Removed from cart',
//     cart_empty: 'Your cart is empty',
//     checkout: 'Checkout',
//     total: 'Total',
//     view_cart: 'View Cart',
//     delivering_to: 'Delivering to',
//     select_location: 'Select Location',
//     no_results: 'No locations found',
//     try_different: 'Try a different search term',
//     currency: 'Currency',
//     language: 'Language',
//     country: 'Country',
//     location: 'Location',
//     select_currency: 'Select your preferred currency',
//     select_language: 'Select your preferred language',
//     current: 'Current',
//     close: 'Close',
//     retry: 'Retry',
//     update: 'Update',
//     your_location: 'Your Location',
//     search_location: 'Search for a location...',
//     auto_detect: 'Auto-detect',
//     view_map: 'View Map',
//     detecting: 'Detecting...',
//     getting_gps: 'Getting GPS...',
//     found: 'found',
//     detected: 'detected',
//     selected: 'selected',
//     ip_based: 'IP based - may be inaccurate',
//     may_be_inaccurate: 'May be inaccurate',
//     enable_gps_tip: 'Tip: Enable GPS for accurate location',
//     unknown_location: 'Unknown Location',
//     low_accuracy: 'Location accuracy is low. Please enable high accuracy GPS.',
//     gps_failed: 'GPS location failed',
//     permission_denied: 'Location permission denied. Please allow location access.',
//     position_unavailable: 'Location information is unavailable.',
//     timeout: 'Location request timed out. Please try again.',
//     unable_to_detect: 'Unable to detect location',
//     could_not_detect: 'Could not detect location',
//     detection_failed: 'Location detection failed',
//     admin: 'Administrator',
//     search: 'Search',
//     all: 'All',
//     in_stock: 'In Stock',
//     out_of_stock: 'Out of Stock',
//     add_to_cart: 'Add to Cart',
//     buy_now: 'Buy Now',
//     description: 'Description',
//     reviews: 'Reviews',
//     rating: 'Rating',
//     shipping: 'Shipping',
//     returns: 'Returns',
//     payment: 'Payment',
//     order_summary: 'Order Summary',
//     subtotal: 'Subtotal',
//     discount: 'Discount',
//     delivery_charge: 'Delivery Charge',
//     proceed_to_checkout: 'Proceed to Checkout',
//     continue_shopping: 'Continue Shopping',
//     place_order: 'Place Order',
//     order_confirmed: 'Order Confirmed',
//     order_cancelled: 'Order Cancelled',
//     track_your_order: 'Track Your Order',
//     order_id: 'Order ID',
//     order_date: 'Order Date',
//     order_status: 'Order Status',
//     delivered: 'Delivered',
//     shipped: 'Shipped',
//     processing: 'Processing',
//     pending: 'Pending',
//     cancelled: 'Cancelled',
//     refunded: 'Refunded',
//     // Home Page
//     shop_description: "India's premium online shopping destination",
//     home_title: 'Sombustore - Premium Products & Amazing Offers',
//     home_description: "Welcome to Sombustore - India's premium online shopping destination.",
//     coming_soon: '🚀 Coming Soon',
//     discover_your: 'Discover Your',
//     perfect_style: 'Perfect Style',
//     hero_description: "🎨 We're crafting something amazing! Our store is launching soon with exclusive collections.",
//     view_collections: 'View Collections',
//     soon: 'Soon',
//     happy_customers: 'Happy Customers',
//     brands: 'Brands',
//     delivery: 'Delivery*',
//     free_shipping: 'Free Shipping',
//     free_shipping_desc: 'On orders above ₹500',
//     secure_payment: 'Secure Payment',
//     secure_payment_desc: '100% Secure',
//     support: '24/7 Support',
//     support_desc: 'Dedicated team',
//     easy_returns: 'Easy Returns',
//     easy_returns_desc: '7 days return',
//     no_products: 'No Products Available',
//     curating_collection: "We're currently curating the best collection for you.",
//     under_construction: 'Our store is under construction. Check back soon for amazing products!',
//     launching_soon: "We're launching soon",
//     stay_tuned: 'Stay tuned!',
//     progress: 'Progress',
//     almost_there: "Almost there! We're preparing something special for you.",
//     current_language: 'Current Language',
//     current_currency: 'Current Currency',
//   },
//   hi: {
//     home: 'होम',
//     products: 'उत्पाद',
//     orders: 'ऑर्डर',
//     track: 'ट्रैक ऑर्डर',
//     login: 'लॉगिन',
//     logout: 'लॉगआउट',
//     wishlist: 'विशलिस्ट',
//     filters: 'फ़िल्टर',
//     categories: 'श्रेणियाँ',
//     all_categories: 'सभी श्रेणियाँ',
//     price_range: 'मूल्य सीमा',
//     min_price: 'न्यूनतम मूल्य',
//     max_price: 'अधिकतम मूल्य',
//     sort_by: 'क्रमबद्ध करें',
//     newest_first: 'नवीनतम पहले',
//     price_low_to_high: 'कम से ज्यादा कीमत',
//     price_high_to_low: 'ज्यादा से कम कीमत',
//     name_a_to_z: 'नाम A से Z',
//     apply_filters: 'फ़िल्टर लागू करें',
//     clear_all: 'सभी फ़िल्टर साफ़ करें',
//     search_products: 'उत्पाद, ब्रांड और श्रेणियाँ खोजें...',
//     your_profile: 'आपकी प्रोफ़ाइल',
//     your_orders: 'आपके ऑर्डर',
//     track_order: 'ऑर्डर ट्रैक करें',
//     admin_dashboard: 'एडमिन डैशबोर्ड',
//     select_language: 'भाषा चुनें',
//     shop_now: 'अभी खरीदें',
//     featured: 'विशेष',
//     trending: 'ट्रेंडिंग',
//     new_arrivals: 'नए आगमन',
//     best_sellers: 'बेस्ट सेलर्स',
//     added_to_cart: 'कार्ट में जोड़ा गया',
//     removed_from_cart: 'कार्ट से हटाया गया',
//     cart_empty: 'आपकी कार्ट खाली है',
//     checkout: 'चेकआउट',
//     total: 'कुल',
//     view_cart: 'कार्ट देखें',
//     delivering_to: 'डिलीवरी हो रही है',
//     select_location: 'स्थान चुनें',
//     no_results: 'कोई स्थान नहीं मिला',
//     try_different: 'अलग शब्द खोजें',
//     currency: 'मुद्रा',
//     language: 'भाषा',
//     country: 'देश',
//     location: 'स्थान',
//     select_currency: 'अपनी पसंदीदा मुद्रा चुनें',
//     select_language: 'अपनी पसंदीदा भाषा चुनें',
//     current: 'वर्तमान',
//     close: 'बंद करें',
//     retry: 'पुनः प्रयास करें',
//     update: 'अपडेट करें',
//     your_location: 'आपका स्थान',
//     search_location: 'स्थान खोजें...',
//     auto_detect: 'स्वतः पहचानें',
//     view_map: 'मानचित्र देखें',
//     detecting: 'पहचान हो रही है...',
//     getting_gps: 'GPS प्राप्त हो रहा है...',
//     found: 'मिला',
//     detected: 'पहचाना गया',
//     selected: 'चुना गया',
//     ip_based: 'IP आधारित - अशुद्ध हो सकता है',
//     may_be_inaccurate: 'अशुद्ध हो सकता है',
//     enable_gps_tip: 'टिप: सटीक स्थान के लिए GPS सक्षम करें',
//     unknown_location: 'अज्ञात स्थान',
//     low_accuracy: 'स्थान सटीकता कम है। कृपया उच्च सटीकता GPS सक्षम करें।',
//     gps_failed: 'GPS स्थान विफल',
//     permission_denied: 'स्थान अनुमति अस्वीकृत। कृपया स्थान पहुंच की अनुमति दें।',
//     position_unavailable: 'स्थान जानकारी उपलब्ध नहीं है।',
//     timeout: 'स्थान अनुरोध समय समाप्त। कृपया पुनः प्रयास करें।',
//     unable_to_detect: 'स्थान का पता लगाने में असमर्थ',
//     could_not_detect: 'स्थान का पता नहीं लगा सके',
//     detection_failed: 'स्थान का पता लगाना विफल',
//     admin: 'प्रशासक',
//     search: 'खोजें',
//     all: 'सभी',
//     in_stock: 'स्टॉक में',
//     out_of_stock: 'स्टॉक से बाहर',
//     add_to_cart: 'कार्ट में डालें',
//     buy_now: 'अभी खरीदें',
//     description: 'विवरण',
//     reviews: 'समीक्षाएँ',
//     rating: 'रेटिंग',
//     shipping: 'शिपिंग',
//     returns: 'रिटर्न',
//     payment: 'भुगतान',
//     order_summary: 'ऑर्डर सारांश',
//     subtotal: 'उप-योग',
//     discount: 'छूट',
//     delivery_charge: 'डिलीवरी शुल्क',
//     proceed_to_checkout: 'चेकआउट पर जाएं',
//     continue_shopping: 'खरीदारी जारी रखें',
//     place_order: 'ऑर्डर दें',
//     order_confirmed: 'ऑर्डर पुष्टि हुई',
//     order_cancelled: 'ऑर्डर रद्द',
//     track_your_order: 'अपना ऑर्डर ट्रैक करें',
//     order_id: 'ऑर्डर ID',
//     order_date: 'ऑर्डर तिथि',
//     order_status: 'ऑर्डर स्थिति',
//     delivered: 'डिलीवर हो गया',
//     shipped: 'शिप हो गया',
//     processing: 'प्रोसेस हो रहा है',
//     pending: 'लंबित',
//     cancelled: 'रद्द',
//     refunded: 'रिफंड हुआ',
//     // Home Page
//     shop_description: "भारत का प्रीमियम ऑनलाइन शॉपिंग गंतव्य",
//     home_title: 'Sombustore - प्रीमियम उत्पाद और शानदार ऑफर्स',
//     home_description: 'Sombustore में आपका स्वागत है - भारत का प्रीमियम ऑनलाइन शॉपिंग गंतव्य।',
//     coming_soon: '🚀 जल्द आ रहा है',
//     discover_your: 'खोजें अपनी',
//     perfect_style: 'परफेक्ट स्टाइल',
//     hero_description: "🎨 हम कुछ अद्भुत बना रहे हैं! हमारा स्टोर जल्द ही एक्सक्लूसिव कलेक्शन के साथ लॉन्च हो रहा है।",
//     view_collections: 'कलेक्शन देखें',
//     soon: 'जल्द',
//     happy_customers: 'खुश ग्राहक',
//     brands: 'ब्रांड्स',
//     delivery: 'डिलीवरी*',
//     free_shipping: 'मुफ्त शिपिंग',
//     free_shipping_desc: '₹500 से अधिक के ऑर्डर पर',
//     secure_payment: 'सुरक्षित भुगतान',
//     secure_payment_desc: '100% सुरक्षित',
//     support: '24/7 सहायता',
//     support_desc: 'समर्पित टीम',
//     easy_returns: 'आसान रिटर्न',
//     easy_returns_desc: '7 दिन रिटर्न',
//     no_products: 'कोई उत्पाद उपलब्ध नहीं',
//     curating_collection: "हम आपके लिए सबसे अच्छा कलेक्शन तैयार कर रहे हैं।",
//     under_construction: 'हमारा स्टोर निर्माणाधीन है। जल्द ही अद्भुत उत्पादों के लिए वापस आएं!',
//     launching_soon: "हम जल्द ही लॉन्च कर रहे हैं",
//     stay_tuned: 'बने रहें!',
//     progress: 'प्रगति',
//     almost_there: "बस कुछ ही दूरी पर! हम आपके लिए कुछ खास तैयार कर रहे हैं।",
//     current_language: 'वर्तमान भाषा',
//     current_currency: 'वर्तमान मुद्रा',
//   },
//   ta: {
//     home: 'முகப்பு',
//     products: 'தயாரிப்புகள்',
//     orders: 'ஆர்டர்கள்',
//     track: 'ஆர்டரை கண்காணி',
//     login: 'உள்நுழை',
//     logout: 'வெளியேறு',
//     wishlist: 'விருப்ப பட்டியல்',
//     filters: 'வடிப்பான்கள்',
//     categories: 'வகைகள்',
//     all_categories: 'அனைத்து வகைகளும்',
//     price_range: 'விலை வரம்பு',
//     min_price: 'குறைந்தபட்ச விலை',
//     max_price: 'அதிகபட்ச விலை',
//     sort_by: 'வரிசைப்படுத்து',
//     newest_first: 'புதியவை முதலில்',
//     price_low_to_high: 'குறைந்த விலையில் இருந்து உயர்',
//     price_high_to_low: 'உயர் விலையில் இருந்து குறைந்த',
//     name_a_to_z: 'பெயர் A முதல் Z',
//     apply_filters: 'வடிப்பான்களை பயன்படுத்து',
//     clear_all: 'அனைத்து வடிப்பான்களையும் அழி',
//     search_products: 'தயாரிப்புகள், பிராண்டுகள் மற்றும் வகைகளை தேடுங்கள்...',
//     your_profile: 'உங்கள் சுயவிவரம்',
//     your_orders: 'உங்கள் ஆர்டர்கள்',
//     track_order: 'ஆர்டரை கண்காணி',
//     admin_dashboard: 'நிர்வாகி கட்டுப்பாட்டு பலகை',
//     select_language: 'மொழியை தேர்ந்தெடுக்கவும்',
//     shop_now: 'இப்போது வாங்க',
//     featured: 'சிறப்பு',
//     trending: 'பிரபலமானது',
//     new_arrivals: 'புதிய வருகை',
//     best_sellers: 'சிறந்த விற்பனையாளர்கள்',
//     added_to_cart: 'கார்டில் சேர்க்கப்பட்டது',
//     removed_from_cart: 'கார்டில் இருந்து நீக்கப்பட்டது',
//     cart_empty: 'உங்கள் கார்ட் காலியாக உள்ளது',
//     checkout: 'கட்டணம் செலுத்து',
//     total: 'மொத்தம்',
//     view_cart: 'கார்டை காண்க',
//     delivering_to: 'டெலிவரி செய்யப்படுகிறது',
//     select_location: 'இருப்பிடத்தை தேர்ந்தெடுக்கவும்',
//     no_results: 'இருப்பிடங்கள் எதுவும் இல்லை',
//     try_different: 'வேறு சொல்லை முயற்சிக்கவும்',
//     currency: 'நாணயம்',
//     language: 'மொழி',
//     country: 'நாடு',
//     location: 'இருப்பிடம்',
//     select_currency: 'உங்கள் விருப்ப நாணயத்தை தேர்ந்தெடுக்கவும்',
//     select_language: 'உங்கள் விருப்ப மொழியை தேர்ந்தெடுக்கவும்',
//     current: 'தற்போதைய',
//     close: 'மூடு',
//     retry: 'மீண்டும் முயற்சி செய்',
//     update: 'புதுப்பி',
//     your_location: 'உங்கள் இருப்பிடம்',
//     search_location: 'இருப்பிடத்தை தேடு...',
//     auto_detect: 'தானாக கண்டறி',
//     view_map: 'வரைபடத்தை காண்க',
//     detecting: 'கண்டறிகிறது...',
//     getting_gps: 'GPS பெறுகிறது...',
//     found: 'கண்டுபிடிக்கப்பட்டது',
//     detected: 'கண்டறியப்பட்டது',
//     selected: 'தேர்ந்தெடுக்கப்பட்டது',
//     ip_based: 'IP அடிப்படையில் - தவறாக இருக்கலாம்',
//     may_be_inaccurate: 'தவறாக இருக்கலாம்',
//     enable_gps_tip: 'குறிப்பு: துல்லியமான இருப்பிடத்திற்கு GPS ஐ இயக்கவும்',
//     unknown_location: 'அறியப்படாத இருப்பிடம்',
//     low_accuracy: 'இருப்பிட துல்லியம் குறைவாக உள்ளது. தயவுசெய்து உயர் துல்லிய GPS ஐ இயக்கவும்.',
//     gps_failed: 'GPS இருப்பிடம் தோல்வியடைந்தது',
//     permission_denied: 'இருப்பிட அனுமதி மறுக்கப்பட்டது. தயவுசெய்து இருப்பிட அணுகலை அனுமதிக்கவும்.',
//     position_unavailable: 'இருப்பிட தகவல் கிடைக்கவில்லை.',
//     timeout: 'இருப்பிட கோரிக்கை நேரம் முடிந்தது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
//     unable_to_detect: 'இருப்பிடத்தை கண்டறிய முடியவில்லை',
//     could_not_detect: 'இருப்பிடத்தை கண்டறிய முடியவில்லை',
//     detection_failed: 'இருப்பிட கண்டறிதல் தோல்வியடைந்தது',
//     admin: 'நிர்வாகி',
//     search: 'தேடு',
//     all: 'அனைத்தும்',
//     in_stock: 'கையிருப்பில் உள்ளது',
//     out_of_stock: 'கையிருப்பில் இல்லை',
//     add_to_cart: 'கார்டில் சேர்',
//     buy_now: 'இப்போது வாங்க',
//     description: 'விளக்கம்',
//     reviews: 'விமர்சனங்கள்',
//     rating: 'மதிப்பீடு',
//     shipping: 'கப்பல்',
//     returns: 'திரும்பப் பெறுதல்',
//     payment: 'கட்டணம்',
//     order_summary: 'ஆர்டர் சுருக்கம்',
//     subtotal: 'துணை மொத்தம்',
//     discount: 'தள்ளுபடி',
//     delivery_charge: 'டெலிவரி கட்டணம்',
//     proceed_to_checkout: 'செலுத்துவதற்கு செல்லவும்',
//     continue_shopping: 'தொடர்ந்து ஷாப்பிங் செய்யுங்கள்',
//     place_order: 'ஆர்டர் செய்யுங்கள்',
//     order_confirmed: 'ஆர்டர் உறுதி செய்யப்பட்டது',
//     order_cancelled: 'ஆர்டர் ரத்து செய்யப்பட்டது',
//     track_your_order: 'உங்கள் ஆர்டரை கண்காணிக்கவும்',
//     order_id: 'ஆர்டர் ID',
//     order_date: 'ஆர்டர் தேதி',
//     order_status: 'ஆர்டர் நிலை',
//     delivered: 'டெலிவரி செய்யப்பட்டது',
//     shipped: 'அனுப்பப்பட்டது',
//     processing: 'செயலாக்கம்',
//     pending: 'நிலுவையில்',
//     cancelled: 'ரத்து செய்யப்பட்டது',
//     refunded: 'பணம் திருப்பி வழங்கப்பட்டது',
//     // Home Page
//     shop_description: "இந்தியாவின் பிரீமியம் ஆன்லைன் ஷாப்பிங் இடம்",
//     home_title: 'Sombustore - பிரீமியம் தயாரிப்புகள் மற்றும் அற்புதமான சலுகைகள்',
//     home_description: 'Sombustore - இந்தியாவின் பிரீமியம் ஆன்லைன் ஷாப்பிங் இடத்திற்கு உங்களை வரவேற்கிறோம்.',
//     coming_soon: '🚀 விரைவில் வருகிறது',
//     discover_your: 'உங்களின்',
//     perfect_style: 'பெர்ஃபெக்ட் ஸ்டைலை கண்டறியுங்கள்',
//     hero_description: "🎨 நாங்கள் அற்புதமான ஒன்றை உருவாக்குகிறோம்! எங்கள் ஸ்டோர் விரைவில் பிரத்தியேக சேகரிப்புகளுடன் திறக்கப்படுகிறது.",
//     view_collections: 'சேகரிப்புகளைக் காண்க',
//     soon: 'விரைவில்',
//     happy_customers: 'மகிழ்ச்சியான வாடிக்கையாளர்கள்',
//     brands: 'பிராண்டுகள்',
//     delivery: 'டெலிவரி*',
//     free_shipping: 'இலவச டெலிவரி',
//     free_shipping_desc: '₹500 க்கு மேல் ஆர்டர்களில்',
//     secure_payment: 'பாதுகாப்பான கட்டணம்',
//     secure_payment_desc: '100% பாதுகாப்பானது',
//     support: '24/7 ஆதரவு',
//     support_desc: 'அர்ப்பணிப்பு குழு',
//     easy_returns: 'எளிதான ரிட்டர்ன்',
//     easy_returns_desc: '7 நாட்கள் ரிட்டர்ன்',
//     no_products: 'தயாரிப்புகள் எதுவும் இல்லை',
//     curating_collection: "நாங்கள் உங்களுக்காக சிறந்த சேகரிப்புகளை தயாரித்து வருகிறோம்.",
//     under_construction: 'எங்கள் ஸ்டோர் கட்டுமானத்தில் உள்ளது. விரைவில் அற்புதமான தயாரிப்புகளுக்கு திரும்பி வாருங்கள்!',
//     launching_soon: "நாங்கள் விரைவில் திறக்கிறோம்",
//     stay_tuned: 'காத்திருங்கள்!',
//     progress: 'முன்னேற்றம்',
//     almost_there: "கிட்டத்தட்ட முடிந்துவிட்டது! நாங்கள் உங்களுக்காக சிறப்பான ஒன்றை தயாரித்து வருகிறோம்.",
//     current_language: 'தற்போதைய மொழி',
//     current_currency: 'தற்போதைய நாணயம்',
//   },
//   te: {
//     home: 'హోమ్',
//     products: 'ఉత్పత్తులు',
//     orders: 'ఆర్డర్లు',
//     track: 'ఆర్డర్ ట్రాక్',
//     login: 'లాగిన్',
//     logout: 'లాగౌట్',
//     wishlist: 'విష్‌లిస్ట్',
//     filters: 'ఫిల్టర్లు',
//     categories: 'వర్గాలు',
//     all_categories: 'అన్ని వర్గాలు',
//     price_range: 'ధర పరిధి',
//     min_price: 'కనిష్ట ధర',
//     max_price: 'గరిష్ట ధర',
//     sort_by: 'క్రమీకరించు',
//     newest_first: 'కొత్తవి మొదట',
//     price_low_to_high: 'తక్కువ నుండి ఎక్కువ ధర',
//     price_high_to_low: 'ఎక్కువ నుండి తక్కువ ధర',
//     name_a_to_z: 'పేరు A నుండి Z',
//     apply_filters: 'ఫిల్టర్లు వర్తింపజేయి',
//     clear_all: 'అన్ని ఫిల్టర్లు క్లియర్',
//     search_products: 'ఉత్పత్తులు, బ్రాండ్‌లు మరియు వర్గాలను శోధించండి...',
//     your_profile: 'మీ ప్రొఫైల్',
//     your_orders: 'మీ ఆర్డర్లు',
//     track_order: 'ఆర్డర్ ట్రాక్',
//     admin_dashboard: 'నిర్వాహక డాష్‌బోర్డ్',
//     select_language: 'భాషను ఎంచుకోండి',
//     shop_now: 'ఇప్పుడే కొనుగోలు చేయండి',
//     featured: 'ప్రత్యేక',
//     trending: 'ట్రెండింగ్',
//     new_arrivals: 'కొత్త ఆగమనాలు',
//     best_sellers: 'అత్యంత అమ్ముడైనవి',
//     added_to_cart: 'కార్ట్‌కి జోడించబడింది',
//     removed_from_cart: 'కార్ట్ నుండి తీసివేయబడింది',
//     cart_empty: 'మీ కార్ట్ ఖాళీగా ఉంది',
//     checkout: 'చెకౌట్',
//     total: 'మొత్తం',
//     view_cart: 'కార్ట్ వీక్షించండి',
//     delivering_to: 'డెలివరీ చేస్తున్నాము',
//     select_location: 'స్థానాన్ని ఎంచుకోండి',
//     no_results: 'స్థానాలు కనుగొనబడలేదు',
//     try_different: 'వేరే పదాన్ని ప్రయత్నించండి',
//     currency: 'కరెన్సీ',
//     language: 'భాష',
//     country: 'దేశం',
//     location: 'స్థానం',
//     select_currency: 'మీకు నచ్చిన కరెన్సీని ఎంచుకోండి',
//     select_language: 'మీకు నచ్చిన భాషను ఎంచుకోండి',
//     current: 'ప్రస్తుత',
//     close: 'మూసివేయి',
//     retry: 'మళ్ళీ ప్రయత్నించండి',
//     update: 'అప్‌డేట్',
//     your_location: 'మీ స్థానం',
//     search_location: 'స్థానం కోసం శోధించండి...',
//     auto_detect: 'ఆటో-గుర్తించు',
//     view_map: 'మ్యాప్ చూడండి',
//     detecting: 'గుర్తిస్తోంది...',
//     getting_gps: 'GPS పొందుతోంది...',
//     found: 'కనుగొనబడింది',
//     detected: 'గుర్తించబడింది',
//     selected: 'ఎంచుకోబడింది',
//     ip_based: 'IP ఆధారంగా - తప్పు కావచ్చు',
//     may_be_inaccurate: 'తప్పు కావచ్చు',
//     enable_gps_tip: 'చిట్కా: ఖచ్చితమైన స్థానం కోసం GPS ని ప్రారంభించండి',
//     unknown_location: 'తెలియని స్థానం',
//     low_accuracy: 'స్థానం ఖచ్చితత్వం తక్కువగా ఉంది. దయచేసి అధిక ఖచ్చితత్వ GPS ని ప్రారంభించండి.',
//     gps_failed: 'GPS స్థానం విఫలమైంది',
//     permission_denied: 'స్థాన అనుమతి తిరస్కరించబడింది. దయచేసి స్థాన ప్రాప్తిని అనుమతించండి.',
//     position_unavailable: 'స్థాన సమాచారం అందుబాటులో లేదు.',
//     timeout: 'స్థాన అభ్యర్థన సమయం ముగిసింది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
//     unable_to_detect: 'స్థానాన్ని గుర్తించలేకపోయింది',
//     could_not_detect: 'స్థానాన్ని గుర్తించలేకపోయింది',
//     detection_failed: 'స్థాన గుర్తింపు విఫలమైంది',
//     admin: 'నిర్వాహకుడు',
//     search: 'శోధించు',
//     all: 'అన్నీ',
//     in_stock: 'స్టాక్‌లో ఉంది',
//     out_of_stock: 'స్టాక్‌లో లేదు',
//     add_to_cart: 'కార్ట్‌కి జోడించు',
//     buy_now: 'ఇప్పుడే కొనుగోలు చేయండి',
//     description: 'వివరణ',
//     reviews: 'సమీక్షలు',
//     rating: 'రేటింగ్',
//     shipping: 'షిప్పింగ్',
//     returns: 'తిరిగి ఇవ్వడం',
//     payment: 'చెల్లింపు',
//     order_summary: 'ఆర్డర్ సారాంశం',
//     subtotal: 'ఉప-మొత్తం',
//     discount: 'తగ్గింపు',
//     delivery_charge: 'డెలివరీ ఛార్జీ',
//     proceed_to_checkout: 'చెకౌట్‌కి కొనసాగండి',
//     continue_shopping: 'షాపింగ్ కొనసాగించండి',
//     place_order: 'ఆర్డర్ పెట్టండి',
//     order_confirmed: 'ఆర్డర్ నిర్ధారించబడింది',
//     order_cancelled: 'ఆర్డర్ రద్దు చేయబడింది',
//     track_your_order: 'మీ ఆర్డర్‌ను ట్రాక్ చేయండి',
//     order_id: 'ఆర్డర్ ID',
//     order_date: 'ఆర్డర్ తేదీ',
//     order_status: 'ఆర్డర్ స్థితి',
//     delivered: 'డెలివరీ చేయబడింది',
//     shipped: 'షిప్ చేయబడింది',
//     processing: 'ప్రాసెసింగ్',
//     pending: 'పెండింగ్',
//     cancelled: 'రద్దు చేయబడింది',
//     refunded: 'రిఫండ్ చేయబడింది',
//     // Home Page
//     shop_description: "భారతదేశం యొక్క ప్రీమియం ఆన్లైన్ షాపింగ్ గమ్యం",
//     home_title: 'Sombustore - ప్రీమియం ఉత్పత్తులు మరియు అద్భుతమైన ఆఫర్లు',
//     home_description: 'Sombustore - భారతదేశం యొక్క ప్రీమియం ఆన్లైన్ షాపింగ్ గమ్యానికి స్వాగతం.',
//     coming_soon: '🚀 త్వరలో వస్తుంది',
//     discover_your: 'మీ',
//     perfect_style: 'పర్ఫెక్ట్ స్టైల్ ను కనుగొనండి',
//     hero_description: "🎨 మేము అద్భుతమైన దానిని సృష్టిస్తున్నాము! మా స్టోర్ త్వరలో ప్రత్యేక కలెక్షన్‌లతో ప్రారంభమవుతుంది.",
//     view_collections: 'కలెక్షన్స్ చూడండి',
//     soon: 'త్వరలో',
//     happy_customers: 'సంతోషకరమైన కస్టమర్లు',
//     brands: 'బ్రాండ్లు',
//     delivery: 'డెలివరీ*',
//     free_shipping: 'ఉచిత డెలివరీ',
//     free_shipping_desc: '₹500 పైన ఆర్డర్లపై',
//     secure_payment: 'సురక్షిత చెల్లింపు',
//     secure_payment_desc: '100% సురక్షితం',
//     support: '24/7 సహాయం',
//     support_desc: 'అంకిత బృందం',
//     easy_returns: 'సులభమైన రిటర్న్స్',
//     easy_returns_desc: '7 రోజుల రిటర్న్',
//     no_products: 'ఉత్పత్తులు అందుబాటులో లేవు',
//     curating_collection: "మేము మీ కోసం ఉత్తమ కలెక్షన్‌ను సిద్ధం చేస్తున్నాము.",
//     under_construction: 'మా స్టోర్ నిర్మాణంలో ఉంది. అద్భుతమైన ఉత్పత్తుల కోసం త్వరలో తిరిగి రండి!',
//     launching_soon: "మేము త్వరలో ప్రారంభిస్తున్నాము",
//     stay_tuned: 'వేచి ఉండండి!',
//     progress: 'ప్రగతి',
//     almost_there: "దాదాపు పూర్తయింది! మేము మీ కోసం ప్రత్యేకమైన దానిని సిద్ధం చేస్తున్నాము.",
//     current_language: 'ప్రస్తుత భాష',
//     current_currency: 'ప్రస్తుత కరెన్సీ',
//   },
//   ml: {
//     home: 'ഹോം',
//     products: 'ഉൽപ്പന്നങ്ങൾ',
//     orders: 'ഓർഡറുകൾ',
//     track: 'ഓർഡർ ട്രാക്ക്',
//     login: 'ലോഗിൻ',
//     logout: 'ലോഗൗട്ട്',
//     wishlist: 'വിഷ്ലിസ്റ്റ്',
//     filters: 'ഫിൽട്ടറുകൾ',
//     categories: 'വിഭാഗങ്ങൾ',
//     all_categories: 'എല്ലാ വിഭാഗങ്ങളും',
//     price_range: 'വില പരിധി',
//     min_price: 'ഏറ്റവും കുറഞ്ഞ വില',
//     max_price: 'ഏറ്റവും കൂടിയ വില',
//     sort_by: 'അടുക്കുക',
//     newest_first: 'ഏറ്റവും പുതിയത് ആദ്യം',
//     price_low_to_high: 'കുറഞ്ഞതിൽ നിന്ന് ഉയർന്ന വില',
//     price_high_to_low: 'ഉയർന്നതിൽ നിന്ന് കുറഞ്ഞ വില',
//     name_a_to_z: 'പേര് A മുതൽ Z',
//     apply_filters: 'ഫിൽട്ടറുകൾ പ്രയോഗിക്കുക',
//     clear_all: 'എല്ലാ ഫിൽട്ടറുകളും മായ്ക്കുക',
//     search_products: 'ഉൽപ്പന്നങ്ങൾ, ബ്രാൻഡുകൾ, വിഭാഗങ്ങൾ എന്നിവ തിരയുക...',
//     your_profile: 'നിങ്ങളുടെ പ്രൊഫൈൽ',
//     your_orders: 'നിങ്ങളുടെ ഓർഡറുകൾ',
//     track_order: 'ഓർഡർ ട്രാക്ക്',
//     admin_dashboard: 'അഡ്മിൻ ഡാഷ്‌ബോർഡ്',
//     select_language: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
//     shop_now: 'ഇപ്പോൾ വാങ്ങുക',
//     featured: 'ഫീച്ചർ ചെയ്തത്',
//     trending: 'ട്രെൻഡിംഗ്',
//     new_arrivals: 'പുതിയ എത്തിച്ചേരലുകൾ',
//     best_sellers: 'ബെസ്റ്റ് സെല്ലേഴ്സ്',
//     added_to_cart: 'കാർട്ടിൽ ചേർത്തു',
//     removed_from_cart: 'കാർട്ടിൽ നിന്ന് നീക്കം ചെയ്തു',
//     cart_empty: 'നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്',
//     checkout: 'ചെക്കൗട്ട്',
//     total: 'ആകെ',
//     view_cart: 'കാർട്ട് കാണുക',
//     delivering_to: 'ഡെലിവറി ചെയ്യുന്നു',
//     select_location: 'സ്ഥാനം തിരഞ്ഞെടുക്കുക',
//     no_results: 'സ്ഥാനങ്ങൾ കണ്ടെത്തിയില്ല',
//     try_different: 'മറ്റൊരു പദം പരീക്ഷിക്കുക',
//     currency: 'കറൻസി',
//     language: 'ഭാഷ',
//     country: 'രാജ്യം',
//     location: 'സ്ഥാനം',
//     select_currency: 'നിങ്ങൾ ഇഷ്ടപ്പെടുന്ന കറൻസി തിരഞ്ഞെടുക്കുക',
//     select_language: 'നിങ്ങൾ ഇഷ്ടപ്പെടുന്ന ഭാഷ തിരഞ്ഞെടുക്കുക',
//     current: 'നിലവിലുള്ള',
//     close: 'അടയ്ക്കുക',
//     retry: 'വീണ്ടും ശ്രമിക്കുക',
//     update: 'അപ്ഡേറ്റ്',
//     your_location: 'നിങ്ങളുടെ സ്ഥാനം',
//     search_location: 'സ്ഥാനം തിരയുക...',
//     auto_detect: 'ഓട്ടോ-കണ്ടെത്തുക',
//     view_map: 'മാപ്പ് കാണുക',
//     detecting: 'കണ്ടെത്തുന്നു...',
//     getting_gps: 'GPS ലഭിക്കുന്നു...',
//     found: 'കണ്ടെത്തി',
//     detected: 'കണ്ടെത്തി',
//     selected: 'തിരഞ്ഞെടുത്തു',
//     ip_based: 'IP അടിസ്ഥാനമാക്കി - കൃത്യമല്ലായിരിക്കാം',
//     may_be_inaccurate: 'കൃത്യമല്ലായിരിക്കാം',
//     enable_gps_tip: 'ടിപ്പ്: കൃത്യമായ സ്ഥാനത്തിന് GPS പ്രവർത്തനക്ഷമമാക്കുക',
//     unknown_location: 'അജ്ഞാത സ്ഥാനം',
//     low_accuracy: 'സ്ഥാന കൃത്യത കുറവാണ്. ദയവായി ഉയർന്ന കൃത്യത GPS പ്രവർത്തനക്ഷമമാക്കുക.',
//     gps_failed: 'GPS സ്ഥാനം പരാജയപ്പെട്ടു',
//     permission_denied: 'സ്ഥാന അനുമതി നിഷേധിച്ചു. ദയവായി സ്ഥാന ആക്സസ് അനുവദിക്കുക.',
//     position_unavailable: 'സ്ഥാന വിവരങ്ങൾ ലഭ്യമല്ല.',
//     timeout: 'സ്ഥാന അഭ്യർത്ഥന സമയം കഴിഞ്ഞു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
//     unable_to_detect: 'സ്ഥാനം കണ്ടെത്താനായില്ല',
//     could_not_detect: 'സ്ഥാനം കണ്ടെത്താനായില്ല',
//     detection_failed: 'സ്ഥാന കണ്ടെത്തൽ പരാജയപ്പെട്ടു',
//     admin: 'അഡ്മിൻ',
//     search: 'തിരയുക',
//     all: 'എല്ലാം',
//     in_stock: 'സ്റ്റോക്കിൽ',
//     out_of_stock: 'സ്റ്റോക്കില്ല',
//     add_to_cart: 'കാർട്ടിൽ ചേർക്കുക',
//     buy_now: 'ഇപ്പോൾ വാങ്ങുക',
//     description: 'വിവരണം',
//     reviews: 'അവലോകനങ്ങൾ',
//     rating: 'റേറ്റിംഗ്',
//     shipping: 'ഷിപ്പിംഗ്',
//     returns: 'തിരികെ നൽകൽ',
//     payment: 'പേയ്മെന്റ്',
//     order_summary: 'ഓർഡർ സംഗ്രഹം',
//     subtotal: 'ഉപ-ആകെ',
//     discount: 'കിഴിവ്',
//     delivery_charge: 'ഡെലിവറി ചാർജ്',
//     proceed_to_checkout: 'ചെക്കൗട്ടിലേക്ക് പോകുക',
//     continue_shopping: 'ഷോപ്പിംഗ് തുടരുക',
//     place_order: 'ഓർഡർ നൽകുക',
//     order_confirmed: 'ഓർഡർ സ്ഥിരീകരിച്ചു',
//     order_cancelled: 'ഓർഡർ റദ്ദാക്കി',
//     track_your_order: 'നിങ്ങളുടെ ഓർഡർ ട്രാക്ക് ചെയ്യുക',
//     order_id: 'ഓർഡർ ID',
//     order_date: 'ഓർഡർ തീയതി',
//     order_status: 'ഓർഡർ നില',
//     delivered: 'ഡെലിവർ ചെയ്തു',
//     shipped: 'ഷിപ്പ് ചെയ്തു',
//     processing: 'പ്രോസസ്സിംഗ്',
//     pending: 'പെൻഡിംഗ്',
//     cancelled: 'റദ്ദാക്കി',
//     refunded: 'റീഫണ്ട് ചെയ്തു',
//     // Home Page
//     shop_description: "ഇന്ത്യയുടെ പ്രീമിയം ഓൺലൈൻ ഷോപ്പിംഗ് ലക്ഷ്യസ്ഥാനം",
//     home_title: 'Sombustore - പ്രീമിയം ഉൽപ്പന്നങ്ങളും അതിശയകരമായ ഓഫറുകളും',
//     home_description: 'Sombustore - ഇന്ത്യയുടെ പ്രീമിയം ഓൺലൈൻ ഷോപ്പിംഗ് ലക്ഷ്യസ്ഥാനത്തിലേക്ക് സ്വാഗതം.',
//     coming_soon: '🚀 ഉടൻ വരുന്നു',
//     discover_your: 'നിങ്ങളുടെ',
//     perfect_style: 'പെർഫെക്റ്റ് സ്റ്റൈൽ കണ്ടെത്തുക',
//     hero_description: "🎨 ഞങ്ങൾ അതിശയകരമായ എന്തോ ഒന്ന് സൃഷ്ടിക്കുന്നു! ഞങ്ങളുടെ സ്റ്റോർ ഉടൻ തന്നെ എക്സ്ക്ലൂസീവ് കളക്ഷനുകളുമായി ലോഞ്ച് ചെയ്യുന്നു.",
//     view_collections: 'കളക്ഷനുകൾ കാണുക',
//     soon: 'ഉടൻ',
//     happy_customers: 'സന്തുഷ്ടരായ ഉപഭോക്താക്കൾ',
//     brands: 'ബ്രാൻഡുകൾ',
//     delivery: 'ഡെലിവറി*',
//     free_shipping: 'സൗജന്യ ഡെലിവറി',
//     free_shipping_desc: '₹500 ന് മുകളിലുള്ള ഓർഡറുകളിൽ',
//     secure_payment: 'സുരക്ഷിത പേയ്മെന്റ്',
//     secure_payment_desc: '100% സുരക്ഷിതം',
//     support: '24/7 പിന്തുണ',
//     support_desc: 'സമർപ്പിത ടീം',
//     easy_returns: 'എളുപ്പമുള്ള റിട്ടേണുകൾ',
//     easy_returns_desc: '7 ദിവസം റിട്ടേൺ',
//     no_products: 'ഉൽപ്പന്നങ്ങൾ ലഭ്യമല്ല',
//     curating_collection: "ഞങ്ങൾ നിങ്ങൾക്കായി മികച്ച കളക്ഷൻ തയ്യാറാക്കുന്നു.",
//     under_construction: 'ഞങ്ങളുടെ സ്റ്റോർ നിർമ്മാണത്തിലാണ്. അതിശയകരമായ ഉൽപ്പന്നങ്ങൾക്കായി ഉടൻ തിരികെ വരൂ!',
//     launching_soon: "ഞങ്ങൾ ഉടൻ ലോഞ്ച് ചെയ്യുന്നു",
//     stay_tuned: 'കാത്തിരിക്കുക!',
//     progress: 'പുരോഗതി',
//     almost_there: "ഏകദേശം പൂർത്തിയായി! ഞങ്ങൾ നിങ്ങൾക്കായി പ്രത്യേകമായ എന്തോ ഒന്ന് തയ്യാറാക്കുന്നു.",
//     current_language: 'നിലവിലെ ഭാഷ',
//     current_currency: 'നിലവിലെ കറൻസി',
//   },
// };

// // ✅ Currency options
// const currencies = [
//   { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
//   { code: 'USD', symbol: '$', name: 'US Dollar' },
//   { code: 'EUR', symbol: '€', name: 'Euro' },
//   { code: 'GBP', symbol: '£', name: 'British Pound' },
//   { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
//   { code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal' },
//   { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
//   { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
// ];

// // ✅ Language options
// const languages = [
//   { code: 'en', name: 'English', flag: '🇬🇧' },
//   { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
//   { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
//   { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
//   { code: 'ml', name: 'മലയാളം', flag: '🇮🇳' },
// ];

// // ✅ Provider Component
// export const AppProvider = ({ children }) => {
//   const [language, setLanguage] = useState('en');
//   const [currency, setCurrency] = useState({ code: 'INR', symbol: '₹' });
//   const [country, setCountry] = useState({ code: 'IN', name: 'India', flag: '🇮🇳' });
//   const [isLoaded, setIsLoaded] = useState(false);

//   // ✅ Load saved preferences on mount
//   useEffect(() => {
//     const savedLanguage = localStorage.getItem('preferredLanguage');
//     const savedCurrency = localStorage.getItem('preferredCurrency');
//     const savedCountry = localStorage.getItem('preferredCountry');
    
//     if (savedLanguage && languages.find(l => l.code === savedLanguage)) {
//       setLanguage(savedLanguage);
//     }
    
//     if (savedCurrency) {
//       try {
//         setCurrency(JSON.parse(savedCurrency));
//       } catch (e) {
//         setCurrency({ code: 'INR', symbol: '₹' });
//       }
//     }
    
//     if (savedCountry) {
//       try {
//         setCountry(JSON.parse(savedCountry));
//       } catch (e) {}
//     }
    
//     setIsLoaded(true);
//   }, []);

//   // ✅ Change language
//   const changeLanguage = (langCode) => {
//     setLanguage(langCode);
//     localStorage.setItem('preferredLanguage', langCode);
    
//     if (typeof window !== 'undefined') {
//       window.dispatchEvent(new CustomEvent('languageChange', {
//         detail: { language: langCode }
//       }));
//     }
//   };

//   // ✅ Change currency
//   const changeCurrency = (currencyData) => {
//     setCurrency(currencyData);
//     localStorage.setItem('preferredCurrency', JSON.stringify(currencyData));
    
//     if (typeof window !== 'undefined') {
//       window.dispatchEvent(new CustomEvent('currencyChange', {
//         detail: { currency: currencyData }
//       }));
//     }
//   };

//   // ✅ Change country
//   const changeCountry = (countryData) => {
//     setCountry(countryData);
//     localStorage.setItem('preferredCountry', JSON.stringify(countryData));
    
//     if (typeof window !== 'undefined') {
//       window.dispatchEvent(new CustomEvent('countryChange', {
//         detail: { country: countryData }
//       }));
//     }
//   };

//   // ✅ Translation function
//   const t = (key) => {
//     return translations[language]?.[key] || translations.en[key] || key;
//   };

//   // ✅ Format price with currency
//   const formatPrice = (amount) => {
//     const symbol = currency.symbol || '₹';
//     return `${symbol} ${Number(amount).toFixed(2)}`;
//   };

//   // ✅ Get current language object
//   const currentLanguage = languages.find(l => l.code === language) || languages[0];

//   // ✅ Get current currency object
//   const currentCurrency = currency;

// const value = {
//   language,
//   currency,
//   country,
//   currentLanguage,
//   currentCurrency,
//   changeLanguage,  // ✅ Make sure this is included
//   changeCurrency,  // ✅ Make sure this is included
//   changeCountry,   // ✅ Make sure this is included
//   setLanguage,
//   setCurrency,
//   setCountry,
//   t,
//   formatPrice,
//   languages,
//   currencies,
//   isLoaded,
// };
//   return (
//     <AppContext.Provider value={value}>
//       {children}
//     </AppContext.Provider>
//   );
// };
// src/context/AppContext.jsx
'use client';

import React, { createContext, useState, useEffect } from 'react';
import toast from 'react-hot-toast';

export const AppContext = createContext();

// ✅ Translations
const translations = {
  en: {
    home: 'Home',
    products: 'Products',
    orders: 'Orders',
    track_order: 'Track Order',
    login: 'Login',
    logout: 'Logout',
    wishlist: 'Wishlist',
    filters: 'Filters',
    categories: 'Categories',
    all_categories: 'All Categories',
    price_range: 'Price Range',
    min_price: 'Min Price',
    max_price: 'Max Price',
    sort_by: 'Sort By',
    newest_first: 'Newest First',
    price_low_to_high: 'Price: Low to High',
    price_high_to_low: 'Price: High to Low',
    name_a_to_z: 'Name: A to Z',
    apply_filters: 'Apply Filters',
    clear_all: 'Clear All Filters',
    search_products: 'Search for products, brands, and categories...',
    your_profile: 'Your Profile',
    your_orders: 'Your Orders',
    admin_dashboard: 'Admin Dashboard',
    select_language: 'Select Language',
    hello: 'Hello',
    sign_in: 'Sign in',
    cart: 'Cart',
    delivering_to: 'Delivering to',
    select_location: 'Select Location',
    currency: 'Currency',
    language: 'Language',
    country: 'Country',
    location: 'Location',
    select_currency: 'Select Currency',
    current: 'Current',
    close: 'Close',
    retry: 'Retry',
    update: 'Update',
    your_location: 'Your Location',
    search_location: 'Search location...',
    auto_detect: 'Auto-detect',
    view_map: 'View Map',
    detecting: 'Detecting...',
    getting_gps: 'Getting GPS...',
    found: 'found',
    detected: 'detected',
    selected: 'selected',
    ip_based: 'IP based - may be inaccurate',
    may_be_inaccurate: 'May be inaccurate',
    enable_gps_tip: 'Enable GPS for accurate location',
    unknown_location: 'Unknown Location',
    admin: 'Administrator',
    search: 'Search',
    all: 'All',
    in_stock: 'In Stock',
    out_of_stock: 'Out of Stock',
    add_to_cart: 'Add to Cart',
    buy_now: 'Buy Now',
    description: 'Description',
    reviews: 'Reviews',
    rating: 'Rating',
    shipping: 'Shipping',
    returns: 'Returns',
    payment: 'Payment',
    order_summary: 'Order Summary',
    subtotal: 'Subtotal',
    discount: 'Discount',
    delivery_charge: 'Delivery Charge',
    proceed_to_checkout: 'Proceed to Checkout',
    continue_shopping: 'Continue Shopping',
    place_order: 'Place Order',
    order_confirmed: 'Order Confirmed',
    order_cancelled: 'Order Cancelled',
    track_your_order: 'Track Your Order',
    order_id: 'Order ID',
    order_date: 'Order Date',
    order_status: 'Order Status',
    delivered: 'Delivered',
    shipped: 'Shipped',
    processing: 'Processing',
    pending: 'Pending',
    cancelled: 'Cancelled',
    refunded: 'Refunded',
    shop_description: "India's premium online shopping destination",
    home_title: 'Sombu Store - Premium Products & Amazing Offers',
    home_description: "Welcome to Sombu Store",
    coming_soon: 'Coming Soon',
    discover_your: 'Discover Your',
    perfect_style: 'Perfect Style',
    hero_description: "We're crafting something amazing!",
    view_collections: 'View Collections',
    soon: 'Soon',
    happy_customers: 'Happy Customers',
    brands: 'Brands',
    delivery: 'Delivery*',
    free_shipping: 'Free Shipping',
    free_shipping_desc: 'On orders above ₹500',
    secure_payment: 'Secure Payment',
    secure_payment_desc: '100% Secure',
    support: '24/7 Support',
    support_desc: 'Dedicated team',
    easy_returns: 'Easy Returns',
    easy_returns_desc: '7 days return',
    no_products: 'No Products Available',
    curating_collection: "We're curating the best collection",
    under_construction: 'Store under construction',
    launching_soon: "Launching soon",
    stay_tuned: 'Stay tuned!',
    progress: 'Progress',
    almost_there: "Almost there!",
    current_language: 'Current Language',
    current_currency: 'Current Currency',
  },
  ta: {
    home: 'முகப்பு',
    products: 'தயாரிப்புகள்',
    orders: 'ஆர்டர்கள்',
    track_order: 'ஆர்டரை கண்காணி',
    login: 'உள்நுழை',
    logout: 'வெளியேறு',
    wishlist: 'விருப்ப பட்டியல்',
    filters: 'வடிப்பான்கள்',
    categories: 'வகைகள்',
    all_categories: 'அனைத்து வகைகளும்',
    price_range: 'விலை வரம்பு',
    min_price: 'குறைந்தபட்ச விலை',
    max_price: 'அதிகபட்ச விலை',
    sort_by: 'வரிசைப்படுத்து',
    newest_first: 'புதியவை முதலில்',
    price_low_to_high: 'குறைந்த விலையில் இருந்து உயர்',
    price_high_to_low: 'உயர் விலையில் இருந்து குறைந்த',
    name_a_to_z: 'பெயர் A முதல் Z',
    apply_filters: 'வடிப்பான்களை பயன்படுத்து',
    clear_all: 'அனைத்து வடிப்பான்களையும் அழி',
    search_products: 'தயாரிப்புகளை தேடுங்கள்...',
    your_profile: 'உங்கள் சுயவிவரம்',
    your_orders: 'உங்கள் ஆர்டர்கள்',
    admin_dashboard: 'நிர்வாகி கட்டுப்பாட்டு பலகை',
    select_language: 'மொழியை தேர்ந்தெடுக்கவும்',
    hello: 'வணக்கம்',
    sign_in: 'உள்நுழையவும்',
    cart: 'கார்ட்',
    delivering_to: 'டெலிவரி செய்யப்படுகிறது',
    select_location: 'இருப்பிடத்தை தேர்ந்தெடுக்கவும்',
    currency: 'நாணயம்',
    language: 'மொழி',
    country: 'நாடு',
    location: 'இருப்பிடம்',
    select_currency: 'நாணயத்தை தேர்ந்தெடுக்கவும்',
    current: 'தற்போதைய',
    close: 'மூடு',
    retry: 'மீண்டும் முயற்சி செய்',
    update: 'புதுப்பி',
    your_location: 'உங்கள் இருப்பிடம்',
    search_location: 'இருப்பிடத்தை தேடு...',
    auto_detect: 'தானாக கண்டறி',
    view_map: 'வரைபடத்தை காண்க',
    detecting: 'கண்டறிகிறது...',
    getting_gps: 'GPS பெறுகிறது...',
    found: 'கண்டுபிடிக்கப்பட்டது',
    detected: 'கண்டறியப்பட்டது',
    selected: 'தேர்ந்தெடுக்கப்பட்டது',
    ip_based: 'IP அடிப்படையில் - தவறாக இருக்கலாம்',
    may_be_inaccurate: 'தவறாக இருக்கலாம்',
    enable_gps_tip: 'துல்லியமான இருப்பிடத்திற்கு GPS ஐ இயக்கவும்',
    unknown_location: 'அறியப்படாத இருப்பிடம்',
    admin: 'நிர்வாகி',
    search: 'தேடு',
    all: 'அனைத்தும்',
    in_stock: 'கையிருப்பில் உள்ளது',
    out_of_stock: 'கையிருப்பில் இல்லை',
    add_to_cart: 'கார்டில் சேர்',
    buy_now: 'இப்போது வாங்க',
    description: 'விளக்கம்',
    reviews: 'விமர்சனங்கள்',
    rating: 'மதிப்பீடு',
    shipping: 'கப்பல்',
    returns: 'திரும்பப் பெறுதல்',
    payment: 'கட்டணம்',
    order_summary: 'ஆர்டர் சுருக்கம்',
    subtotal: 'துணை மொத்தம்',
    discount: 'தள்ளுபடி',
    delivery_charge: 'டெலிவரி கட்டணம்',
    proceed_to_checkout: 'செலுத்துவதற்கு செல்லவும்',
    continue_shopping: 'தொடர்ந்து ஷாப்பிங் செய்யுங்கள்',
    place_order: 'ஆர்டர் செய்யுங்கள்',
    order_confirmed: 'ஆர்டர் உறுதி செய்யப்பட்டது',
    order_cancelled: 'ஆர்டர் ரத்து செய்யப்பட்டது',
    track_your_order: 'உங்கள் ஆர்டரை கண்காணிக்கவும்',
    order_id: 'ஆர்டர் ID',
    order_date: 'ஆர்டர் தேதி',
    order_status: 'ஆர்டர் நிலை',
    delivered: 'டெலிவரி செய்யப்பட்டது',
    shipped: 'அனுப்பப்பட்டது',
    processing: 'செயலாக்கம்',
    pending: 'நிலுவையில்',
    cancelled: 'ரத்து செய்யப்பட்டது',
    refunded: 'பணம் திருப்பி வழங்கப்பட்டது',
    shop_description: "இந்தியாவின் பிரீமியம் ஆன்லைன் ஷாப்பிங் இடம்",
    home_title: 'Sombu Store - பிரீமியம் தயாரிப்புகள்',
    home_description: 'Sombu Store - இந்தியாவின் பிரீமியம் ஆன்லைன் ஷாப்பிங் இடம்',
    coming_soon: '🚀 விரைவில் வருகிறது',
    discover_your: 'உங்களின்',
    perfect_style: 'பெர்ஃபெக்ட் ஸ்டைலை கண்டறியுங்கள்',
    hero_description: "🎨 நாங்கள் அற்புதமான ஒன்றை உருவாக்குகிறோம்!",
    view_collections: 'சேகரிப்புகளைக் காண்க',
    soon: 'விரைவில்',
    happy_customers: 'மகிழ்ச்சியான வாடிக்கையாளர்கள்',
    brands: 'பிராண்டுகள்',
    delivery: 'டெலிவரி*',
    free_shipping: 'இலவச டெலிவரி',
    free_shipping_desc: '₹500 க்கு மேல் ஆர்டர்களில்',
    secure_payment: 'பாதுகாப்பான கட்டணம்',
    secure_payment_desc: '100% பாதுகாப்பானது',
    support: '24/7 ஆதரவு',
    support_desc: 'அர்ப்பணிப்பு குழு',
    easy_returns: 'எளிதான ரிட்டர்ன்',
    easy_returns_desc: '7 நாட்கள் ரிட்டர்ன்',
    no_products: 'தயாரிப்புகள் எதுவும் இல்லை',
    curating_collection: "சிறந்த சேகரிப்புகளை தயாரித்து வருகிறோம்",
    under_construction: 'ஸ்டோர் கட்டுமானத்தில் உள்ளது',
    launching_soon: "விரைவில் திறக்கிறோம்",
    stay_tuned: 'காத்திருங்கள்!',
    progress: 'முன்னேற்றம்',
    almost_there: "கிட்டத்தட்ட முடிந்துவிட்டது!",
    current_language: 'தற்போதைய மொழி',
    current_currency: 'தற்போதைய நாணயம்',
  },
};

// ✅ Currency options
const currencies = [
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
];

// ✅ Language options
const languages = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
];

export const AppProvider = ({ children }) => {
  // ✅ FORCE English as default - ALWAYS
  const [language, setLanguage] = useState('en');
  const [currency, setCurrency] = useState({ code: 'INR', symbol: '₹' });
  const [country, setCountry] = useState({ code: 'IN', name: 'India', flag: '🇮🇳' });
  const [isLoaded, setIsLoaded] = useState(false);
  const [forceUpdate, setForceUpdate] = useState(0);

  // ✅ On mount - ALWAYS set to English
  useEffect(() => {
    if (typeof window !== 'undefined') {
      // ✅ ALWAYS set to English - IGNORE everything else
      console.log('✅ Setting language to English (forced)');
      setLanguage('en');
      localStorage.setItem('preferredLanguage', 'en');
      
      // ✅ Currency
      setCurrency({ code: 'INR', symbol: '₹' });
      localStorage.setItem('preferredCurrency', JSON.stringify({ code: 'INR', symbol: '₹' }));
    }
    
    setIsLoaded(true);
  }, []);

  // ✅ Change language
  const changeLanguage = (langCode) => {
    console.log('🔄 Changing language to:', langCode);
    setLanguage(langCode);
    localStorage.setItem('preferredLanguage', langCode);
    setForceUpdate(prev => prev + 1);
    
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('languageChange', {
        detail: { language: langCode }
      }));
    }
    
    const lang = languages.find(l => l.code === langCode);
    toast.success(`Language changed to ${lang?.name || langCode}`);
  };

  // ✅ Change currency
  const changeCurrency = (currencyData) => {
    setCurrency(currencyData);
    localStorage.setItem('preferredCurrency', JSON.stringify(currencyData));
    setForceUpdate(prev => prev + 1);
    
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('currencyChange', {
        detail: { currency: currencyData }
      }));
    }
  };

  // ✅ Translation function
  const t = (key) => {
    const translation = translations[language]?.[key];
    if (translation) return translation;
    return translations.en[key] || key;
  };

  const formatPrice = (amount) => {
    const symbol = currency.symbol || '₹';
    return `${symbol} ${Number(amount).toFixed(2)}`;
  };

  const currentLanguage = languages.find(l => l.code === language) || languages[0];

  const value = {
    language,
    currency,
    country,
    currentLanguage,
    currentCurrency: currency,
    changeLanguage,
    changeCurrency,
    setLanguage,
    setCurrency,
    setCountry,
    t,
    formatPrice,
    languages,
    currencies,
    isLoaded,
    forceUpdate,
  };

  return (
    <AppContext.Provider value={value}>
      {children}
    </AppContext.Provider>
  );
};